### ISSUE TITLE
Using ResourceBundles with Java Class in SQL Database

### ISSUE THREAD

**Issue by throwaway0294** [janino-compiler/janino#101]
Hello, I'm looking for some help with using ResourceBundles. I have the bundles in the same SQL table as the file calling them, as seen here:

![image](https://user-images.githubusercontent.com/54034956/62878434-0e0a2280-bcf7-11e9-8049-9b079c1e2a88.png)

but when I try to access the bundles like so:

![image](https://user-images.githubusercontent.com/54034956/62878484-2a0dc400-bcf7-11e9-85d8-b822aef51f99.png)

I simply get a can't find bundle error:

![image](https://user-images.githubusercontent.com/54034956/62878512-398d0d00-bcf7-11e9-8a0f-ea73003d31e7.png)

Not even sure if this issue is with Janino or with the way I am calling the bundle but if you could point me in the right direction it would be much appreciated. Thanks!

**Comment by aunkrig** [comment]
Hey there,

are you using `org.codehaus.janino.Compiler`, or `SimpleCompiler`, or `JavaSourceClassLoader`, or `ClassBodyEvaluator`?

**Comment by aunkrig** [comment]
The reason being is that neither the `org.codehaus.janino` nor the `org.codehaus.commons-compiler.jdk` implementation of `ICompilerFactory.newJavaSourceClassLoader()` override `ClassLoader.getResourceAsStream(String resourceName)`.

I now added a mechanism that makes getting resources possible for `AbstractJavaSourceClassLoader`: `setResourceFinder(ResourceFinder)`. Examples of how to use it can be found in `JavaSourceClassLoaderTest`, methods `testBundles1()` and `testBundles2()`.

Please test if that solution works for you!
