### ISSUE TITLE
xlint for java source code

### ISSUE THREAD

**Issue by azthief** [janino-compiler/janino#105]
I want to lint the java source file
Is there any method like "javac -Xlint foo.java" ?

**Comment by aunkrig** [comment]
Yes and no. The `org.codehaus.janino.Compiler(12 params)` constructor takes a „warningHandlePatterns“ parameter which is similar to `-Xlint`, but none of the code examples use that constructor.

You could extend `CompilerSample` to call `ICompiler.setWarningHandler()` similar to the mentioned constructor.

Alternatively, if you want to implement your own checks, you could use the AST as described in „Static code analysis“.
