### ISSUE TITLE
Impossible to build the master

### ISSUE THREAD

**Issue by andsel** [janino-compiler/janino#110]
After a fresh clone of the project, from `janino-parent` if I run `mvn package` I get this error of missed dependency:
```
[ERROR] Plugin de.unkrig.txt2html:txt2html-maven-plugin:0.0.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact de.unkrig.txt2html:txt2html-maven-plugin:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

Artifact `txt2html-maven-plugin` of group`de.unkrig.txt2html` can't to be found https://search.maven.org/search?q=g:de.unkrig.txt2html

**Comment by aunkrig** [comment]
My bad... I included the (experimental) MVN plugin "txt2html", which replaces the ASCII art in https://github.com/janino-compiler/janino/trunk/janino/src/main/javadoc/overview.html

      <pre class="asciiart">{@code .
            +-----------------+                                          +-----------------+
            |                 |\                                         |                 |\
            |   .java files   +-+                                        |   .class files  +-+
            |  on command line  |                                        |   in dest dir     |
            |                   |                                        |                   |
            +-------------------+                                        +-------------------+
                     |                                                            ^
                 parsed by                                                        |
                o.c.j.Parser                                                      |
                   into                                                      written to
                     |                                                            |
                     v                                                            |
    +-------------------------------------+                         +----------------------------+
    | Java.CompilationUnit                |                         | o.c.j.util.ClassFile       |
    +-------------------------------------+                         +----------------------------+
    | Java.PackageMemberTypeDeclaration[] |                         | ClassFile.AttributeInfo[]  |
    |  Java.Annotation[]                  |                         | ClassFile.FieldInfo[]      |
    |  Java.TypeParameter[]               |                         |  ClassFile.AttributeInfo[] |
    |  Java.FieldDeclaration[]            |                         | ClassFile.MethodInfo[]     |
    |   Java.Annotation[]                 |      compiled by        |  ClassFile.AttributeInfo[] |
    |  Java.MemberTypeDeclaration[]       |-- o.c.j.UnitCompiler -->|                            |
    |   ...                               |        into             |                            |
    |  Java.ConstructorDeclarator[]       |                         |                            |
    |   ...                               |                         |                            |
    |  Java.MethodDeclarator[]            |                         |                            |
    |   Java.Annotation[]                 |                         |                            |
    |   Java.TypeParameter[]              |                         |                            |
    |   Java.BlockStatements[]            |                         |                            |
    +-------------------------------------+                         +----------------------------+
      }</pre>

with nice SVG graphics -- but that's still in its infancy.

For now I moved the plugin to a profile "have_txt2html" which is normally not active, so everybody can happily build JANINO.

**Comment by aunkrig** [comment]
Just look at the beautiful SVG graphics on the JANINO JAVADOC page ;-) :

http://janino-compiler.github.io/janino/apidocs/

**Comment by aunkrig** [comment]
Please test if the MASTER no compiles for you.

**Comment by andsel** [comment]
It works! Many thanks @aunkrig, I close the issue.
