### ISSUE TITLE
Get declared variables

### ISSUE THREAD

**Issue by rajatpundir** [janino-compiler/janino#123]
I have an expression which I can evaluate with ExpressionEvaluator()

For example, expression could be something like this: "a + b * c"

Now, I wish to know if janino can tell me what variables it wants from me?

In above case, janino could tell me I have not provided values/types for a, b and c. So that I can then provide it to ExpressionEvaluator(). Is it possible this to achieve with Janino?

**Comment by aunkrig** [comment]
Try this:


http://janino-compiler.github.io/janino/apidocs/org/codehaus/janino/ExpressionEvaluator.html#guessParameterNames(org.codehaus.janino.Scanner)

**Comment by rajatpundir** [comment]
Super thanks! I will try it asap
