### ISSUE TITLE
Janino Sandbox, JVisualVM cannot connect to the application

### ISSUE THREAD

**Issue by SebHeuze** [janino-compiler/janino#124]
Hi,

I was waiting for the new Sandbox of Janino for my application due to some errors with the old one and it's now release.

But, with this Sandbox I can't connect to my application with JVisualVM anymore, and it's a critical issue for me.

This appear to be a JVM Bug, RMI code call getPermissions(CodeSource) that, when not implemented like on Janino default Policy, return a immutable Policy.UNSUPPORTED_EMPTY_COLLECTION. (Then RMI code call .add and it throw exception)
Instead, the java documentation specify that getPermissions(ProtectionDomain) should be called instead (it return new Permissions() when getPermissions(CodeSource) is not implemented.

Elasticsearch proposed a workaround, it's ugly but since the JVM bug is here since a very long time, it's the only way to fix JVisualVM/Jconsole connexion.
https://github.com/elastic/elasticsearch/pull/14274

Do you think Janino can do the same workaround than ElasticSearch (work on my side) ?

**Comment by aunkrig** [comment]
I overrid `getPermissions(CodeSource)` as you proposed... please test.

**Comment by SebHeuze** [comment]
Thanks, I tested and it works
While testing I noticed a small typo : 3.1.3-SNA**S**PSHOT

**Comment by aunkrig** [comment]
Typo in version name is fixed.
