### ISSUE TITLE
How open source projects like logback use JANINO?

### ISSUE THREAD

**Issue by Harlan6** [janino-compiler/janino#125]
I have found in your wiki like this :
Some open source projects that use JANINO
Logback - a Java logging framework intended as a successor to the LOG4J project

**Comment by aunkrig** [comment]
What is your question? If you want to see how LOGBACK uses JANINO, look into its source code -- LOGBACK is open source!

**Comment by Harlan6** [comment]
> What is your question? If you want to see how LOGBACK uses JANINO, look into its source code -- LOGBACK is open source!

Thanks! I will have  try
