### ISSUE TITLE
IllegalArgumentException when calling evalutor.evaluate()

### ISSUE THREAD

**Issue by rajatpundir** [janino-compiler/janino#128]
Recently, I am trying to migrate some code to Kotlin.

I am faced with "java.lang.IllegalArgumentException: wrong number of arguments " when calling below:

evaluator.evaluate(injectedObjects)

Here, injectedObjects is an Array of correct size. Any idea what might be causing this?

**Comment by rajatpundir** [comment]
Temporary Workaround: Declare a static method inside a java class, and use it in Kotlin code.

`
public final class ExpressionUtils {
  public static Object evaluateExpression(ExpressionEvaluator evaluator, Object[] injected_objects) throws InvocationTargetException {
    return evaluator.evaluate(injected_objects);
  }
}`

**Comment by aunkrig** [comment]
Hey Rajat,

that exception means that the number of arguments for ```IExpressionEvaluator.evaluate(Object...)``` is different from the number of parameters passed to ```IExpressionEvaluator.setParameters(String[], Class<?>[])```.

CU Arno

**Comment by rajatpundir** [comment]
Hey Arno,

I had checked the arguments and they are exactly the same, I moved the call to Expression Evaluator in a java file which got it working. I don't know the exact problem but it seems to be a Kotlin issue, not a Janino issue. 

Thanks!

**Comment by rajatpundir** [comment]
One additional query.

I have a few hundred expressions(they grow and reduce a bit) that I would like to cook and evaluate. What would be most efficient way to do this?

Should I cook all the expressions beforehand and store them as serialised objects or how can I avoid performance penalties of cooking expressions often.

**Comment by aunkrig** [comment]
The ExpressionEvaluator can compile *a set of expressions* at once generate one class with N methods. That is tested with up to 10.000 expressions, and scales well.
Caching generated .class files in a permanent storage is probably not (noticeably) faster than compiling expressions when needed.
