### ISSUE TITLE
Outdated javadocs in ExpressionEvaluator

### ISSUE THREAD

**Issue by karussell** [janino-compiler/janino#133]
The javadocs here:
 * https://github.com/janino-compiler/janino/blob/master/commons-compiler-jdk/src/main/java/org/codehaus/commons/compiler/jdk/ExpressionEvaluator.java
 * https://github.com/janino-compiler/janino/blob/master/janino/src/main/java/org/codehaus/janino/ExpressionEvaluator.java

is using the deprecated createFastExpressionEvaluator method.

And regarding the question for the performance difference in commons-compiler-jdk: did you run the test via [JMH](https://github.com/openjdk/jmh)?

**Comment by aunkrig** [comment]
Fixed

**Comment by karussell** [comment]
Thanks!
