### ISSUE TITLE
New BSD License?

### ISSUE THREAD

**Issue by d-huynh** [janino-compiler/janino#136]
Hi,

your license is "New BSD License". Could you clarify, whether this is the BSD-2-Clause or BSD-3-Clause or another?

Thank you so much!

**Comment by vadzim-marchanka** [comment]
Hi, 

I have an issue with the library and my license compliance script. The issue is that pom file points to the github page that can be changed at any time. It becomes not safe to use this library. 

I am proposing two options here:
- replace URL from github site to BSD license site (https://opensource.org/licenses/BSD-2-Clause) in pom file. 
- add License file in each root of jar distributions

Thank you for the great work!

**Comment by aunkrig** [comment]
> Hi,
> 
> your license is "New BSD License". Could you clarify, whether this is the BSD-2-Clause or BSD-3-Clause or another?
> 
> Thank you so much!

See https://opensource.org/licenses/BSD-3-Clause

"New BSD License" === "3-Clause BSD License"

**Comment by aunkrig** [comment]
> * replace URL from github site to BSD license site (https://opensource.org/licenses/BSD-3-Clause) in pom file.

That looks like a bad idea... that page is only a *template* for a License, not the license itself. E.g., the name of the copyright holder is missing.

**Comment by vadzim-marchanka** [comment]
Thank you for the response. If you think that it is a bad idea (the majority of artifacts specify licenses in this way) maybe you can specify the license file in the jar root?

**Comment by aunkrig** [comment]
The MAVEN documentation says:

> name, url and comments: are self explanatory, and have been encountered before in other capacities. Using an SPDX identifier as the license name is recommended.

The "correct" SPDX identifier appears to be "BSD-3-Clause" (see https://spdx.org/licenses/).

However the BSD license text always contains

> Copyright (c) <year> <owner>. All rights reserved.

How can that be a valid license if the year and owner are still variables? I don't get it.

I have the license text in each and every source file, with the correct year and owner (while I am unsure how year and owner of each source file should be chosen - enlightenment appreciated!) Is that enough to document the copyright holder?

Are License and Copyright notice to be handled seaprately?

So many questions...
