### ISSUE TITLE
Without releases and tags in this repo

### ISSUE THREAD

**Issue by harkue** [janino-compiler/janino#138]
Hi, @aunkrig and @zaunerc:

There's no release and tags for janino, so how can we trace version from the source code?

**Comment by oontvoo** [comment]
I agree we haven't been very good at cutting release-branches. (I tried to do that ~4 years ago but didn't have enough bandwidth to keep up )
Perhaps we could set up something like a quarterly release?

But to your question, can you not use the git-revision? I'm not entirely clear what you mean by "trace version from the source".

Thanks,

Vy

**Comment by harkue** [comment]
> I agree we haven't been very good at cutting release-branches. (I tried to do that ~4 years ago but didn't have enough bandwidth to keep up )
> Perhaps we could set up something like a quarterly release?
> 
> But to your question, can you not use the git-revision? I'm not entirely clear what you mean by "trace version from the source".
> 
> Thanks,
> 
> Vy

Thanks for your reply.

I am trying to rebuild 3.1.2 version from source code, but I can's find the tag with this version.

**Comment by aunkrig** [comment]
I just released Janino 3.1.4 and created a branch "3.1.4", and promise to do the same with future versions.
Please verify.

**Comment by aunkrig** [comment]
Same for 3.1.6.

**Comment by harkue** [comment]
Thanks your reply. Sorry for this delay response.

Normally, Other projects use a tag for a release version, such as zlib 1.2.11 using tag `v1.2.11`.

Ref: https://github.com/madler/zlib/tags

so we can use tag `v3.1.4` to trace version 3.1.4 source. Branch 3.1.4 can be used to maintain version 3.1.4's future build.
Tag is read only that be better to used in configuration management.

**Comment by aunkrig** [comment]
Your wish is my command! I just tagged versions 3.1.4 and 3.1.6 as "v...". Anything left to do?

**Comment by wltjr** [comment]
Thank you for the tags/releases, I mentioned it long ago in #37 , now I can delete my fork I only used for tags/releases :) :tada:
