### ISSUE TITLE
The link to the Maven Repository in the project homepage is dead.

### ISSUE THREAD

**Issue by otukatigayim** [janino-compiler/janino#139]
The link to the Maven Repository in the project homepage is dead.

The link to the Maven Repository (http://repo1.maven.org/maven2/org/codehaus/) in the project homepage (https://janino-compiler.github.io/janino/#download) is dead. 
Accessing the dead link returns "501 HTTPS Required".
I changed it to https and was able to access it.

**Comment by aunkrig** [comment]
Fixed. Thanks for the notice!
