### ISSUE TITLE
Unable to convert JSON objects using GSON

### ISSUE THREAD

**Issue by enealDC** [janino-compiler/janino#140]
In Janino - if I have a JSON string and I attempt to map it to a POJO with Gson I receive the following error:

Assignment conversion not possible from type "java.lang.Object" to type "com.google.gson.JsonObject"

**Comment by aunkrig** [comment]
You've ran into one of the limitations of Janino:

From the home page:

> Type arguments: Are parsed, but otherwise ignored. The most significant restriction that follows is that you must cast return values from method invocations, e.g. "(String) myMap.get(key)"
