### ISSUE TITLE
can't parse a < b in some case

### ISSUE THREAD

**Issue by huangfeng1993** [janino-compiler/janino#144]
Method(org.codehaus.janino.Parser#parseRelationalExpression)

    /**
     * <pre>
     *   RelationalExpression :=
     *     ShiftExpression {
     *       'instanceof' ReferenceType
     *       | '&lt;' ShiftExpression [ { ',' TypeArgument } '&gt;' ]
     *       | '&lt;' TypeArgument [ { ',' TypeArgument } '&gt;' ]
     *       | ( '&gt;' | '&lt;=' | '&gt;=' ) ShiftExpression
     *     }
     * </pre>
     */

Why it can't support   ShiftExpression  '&lt;'  ShiftExpression ?

 It cause some case can't work, such as this demo:
```
    public static void main(String[] args) throws IOException, CompileException {

        String code = "public Object[] apply(Object root0) {\n" +

                "int a=1;int b=2 ; " +
                "return new Object[]{a < b,1,2};\n" +
                "}\n";
        final ClassBodyEvaluator cbe = new ClassBodyEvaluator();
        cbe.setClassName("Test");
        cbe.setExtendedClass(Utilities.class);
        cbe.setImplementedInterfaces(new Class[] {Function1.class, Serializable.class});
        cbe.setParentClassLoader(RexExecutable.class.getClassLoader());


        cbe.cook(new Scanner(null, new StringReader(code)));

    }
```

**Comment by aunkrig** [comment]
That was a tough one... I believe I fixed it. Please test. Thank you for your bug report!

**Comment by aunkrig** [comment]
Ping.
