### ISSUE TITLE
No narrowing reference conversion in assignmentConversion()

### ISSUE THREAD

**Issue by barrycg** [janino-compiler/janino#147]
I got an exception 
> Assignment conversion not possible from type "com.sun.jna.Library" to type "com.weld.jna.GeneratedNativeCode$NativeLibrary" 
where invoking the method ClassBodyEvaluator.cook( codeBody ). And part of codeBody is 

```
NativeLibrary nativeLibrary = Native.load("/home/**/**.so", NativeLibrary.class);

 public interface NativeLibrary extends Library {
 ... 
 }
```

I dug a little bit into the source code of Janino, it seems like there's no narrowing referencing conversion in the 
 implementation of assignmentConversion() when it's dealing with the return type of method.

Luckily,  I found a workaround for my problem. ;)

Replacing 

`NativeLibrary nativeLibrary = Native.load("/home/**/**.so", NativeLibrary.class);`

with 
```
com.sun.jna.Library lib = Native.load(\"/home/**/**.so\", NativeLibrary.class);
NativeLibrary nativeLibrary = (NativeLibrary)lib;
```

I‘m just new to Janino,  so I'm really not sure that's a bug or not.  But this workaround is not necessary for javac.

**Comment by aunkrig** [comment]
How is `Native.load()` declared? If it is declared like

    public NativeLibrary load(String path, Class<?> c) { ...

, then Janino is right to state that the invocation is a compile-time error. If, however, the method is declared like

    public <T extends NativeLibrary> T load(String path, Class<T> c) { ...

, then you've run into a limitation of Janino:

> Type arguments: Are parsed, but otherwise ignored. The most significant restriction that follows is that you must cast return values from method invocations, e.g. "(String) myMap.get(key)"

In your case that means: You must type-cast the result of the method invocation, like

    NativeLibrary nl = (NativeLibrary) Native.load(...);

, because Janino ignores the type argument of the static method, and decides that the method returns a `NativeLibrary`.

**Comment by barrycg** [comment]
Actually, the declaration of `Native.load()` is 

`  public static <T extends Library> T load(String name, Class<T> interfaceClass) {
        return load(name, interfaceClass, Collections.<String, Object>emptyMap());
    }`  

I supposed that's exactly the second case that janino ignores the type argument of the static method.

Thanks for your time and attention to this matter! :)
