### ISSUE TITLE
Availability of Janino 2 source code

### ISSUE THREAD

**Issue by sschuberth** [janino-compiler/janino#159]
For reference, I'd like to be able to look at the Janino 2 source code which used to be hosted at http://cvs.codehaus.org/viewrep/janino. Is the code still available from somewhere?

**Comment by aunkrig** [comment]
Hey Sebastian,

the Janino source code repository was transferred from Codehaus' CVS to GITHUB around 2015, but the entire history since January 2005 was kept. I believe I can reconstruct any Janino version 2.2.0 or later. Which exact 2.x version do you want?


Cheers, Arno

**Comment by sschuberth** [comment]
Hi Arno, thanks for the quick response. Right now I'm particularly interested in the source code for version 2.5.10. But actually it would be great if the source code of all 2.x version would be publicly available.

**Comment by aunkrig** [comment]
I just created GIT branches for many old versions, including 2.5.10. Just visit https://github.com/janino-compiler/janino/tree/2.5.10 and, e.g., hit "Code / Download ZIP".

If you need more versions then I can create more branches. There's just so many of them...

**Comment by sschuberth** [comment]
Thanks a lot for the super-fast action!

**Comment by aunkrig** [comment]
That was by accident ;-) . I was just fixing a different issue when yours dropped in.

**Comment by sschuberth** [comment]
Sorry for reopening this, but could we actually get tags (in addition to / instead of branches) in Git for the exact source code that went into a specific binary release? Again, I'm specifically in need for a tag (not a branch) for version 2.5.10 in the context of OSS provenance checks.

**Comment by aunkrig** [comment]
Your wish is my command... tagged all 3.* versions, and many 2.* versions (including 2.5.10).
Please verify!

**Comment by sschuberth** [comment]
Seem to work as expected on our side, thanks a lot (once more)!
