### ISSUE TITLE
Usage on expression compiling without classloading

### ISSUE THREAD

**Issue by Col-E** [janino-compiler/janino#161]
I'm currently evaluating my options for expression support in [a bytecode assembler](https://github.com/Col-E/Recaf/tree/dev3/recaf-assembler). Currently I have this feature to some extent but am becoming frustrated with the limitations and bugs of the current library being leveraged for expression support, Javassist. After some searching I found this project.

The end goal is to support something like this block of code below.
```java
static numToString(I num)V
a:
 // default value for unhandled num, this also defines the variable 'name' for the expr below to use
 ldc "?"
 astore name
b:
 // use expression block so that we don't have to write the switch bytecode by hand
 expr {
    switch(num) {
     case 1: name = "one"; break;
     case 2: name = "two"; break;
     case 3: name = "three"; break;
     case 4: name = "four"; break;
     case 5: name = "five"; break;
    }
 }
c:
 // print the name
 getstatic java/lang/System.out Ljava/io/PrintStream;
 aload name
 invokevirtual java/io/PrintStream.println(Ljava/lang/String;)V
 return
end:
```
Essentially, the user is free to interweave expressions into disassembled bytecode and it will _"just work"_. The way that it currently works is that the method code is visited in a linear fashion from top to bottom. As variable instructions _(astore/aload/etc)_ are found the information about the variable is tracked. When an `expr` block is found [Javassist is fed this information so it is able to compile against those variables](https://github.com/Col-E/Recaf/blob/dev3/recaf-assembler/src/main/java/me/coley/recaf/assemble/compiler/JavassistCompiler.java#L77). In the case of the code example above, `name` is a local variable that should reside at the index of `1` since `0` is reserved by the parameter `num`.

I was curious if Janino could support a use case like mine. I did see that there is `ExpressionEvaluator` but it seems to require that all referenced types be available on the classpath. Since my use case is based on static analysis of random `.class` files I would like to avoid loading things into user's runtimes and instead provide information about types at a lower level. 

If there is any questions or additional details you would like to know about to make an informed answer just let me know.

Any pointers would be greatly appreciated, thanks!

**Comment by aunkrig** [comment]
Hey Matt,

I'm not completely sure what your use case is... You first *disassemble* bytecode, then modify the assembler code, then assemble it back into bytecode? And the latter of these three steps is what RECAF does?

Janino is not prepared to "accept information on local variables" and then use it. Maybe you could fake it by generating a method with N parameters (0=this, 1=name) and then copy and paste the generated bytecode into your output.

The big obstacle that I see here is the goddamn `StackMapTable` attribute, which is mandatory in .class files 7+, for which you must continuously track the state of all local variables and the operand stack. Thus you'd have to merge the `StackMapTable`that Janino generates with that of RECAF -- not easy at all.


CU Arno

**Comment by Col-E** [comment]
> I'm not completely sure what your use case is.

No worries, the project is rather large and complex so that's quite understandable. I'll break it down a bit more; apoligies in advance for this wall of text/video...

**What is the use case?**

Recaf is a bytecode editor and viewer, basically an IDE but the input isn't Java source code, instead it is Java bytecode. You drop in a compiled Java application like a `.jar` file and the rest _should_ be rather intuitive for anyone with experience navigating around an IDE. Unlike other bytecode editors I've tried to make this as beginner friendly as possible and mirror the UI style and interactions of an IDE. The main goal is making things simple by removing more confusing parts of manipulating the class file format. One such feature is the ability to interweave short Java expressions inside the bytecode assembler. This will allow users without much knowledge of the class file format to make simple changes. Here is a demo:

https://user-images.githubusercontent.com/21371686/149754033-c3b16592-577d-4b68-aed7-2ff7b2d86ea8.mp4

So yes the process is essentially as you stated with _"You first disassemble bytecode, then modify the assembler code, then assemble it back into bytecode"_. The reason being this is a tool to make changes to already compiled Java applications. You can see in the demo video I made my change without writing a line of bytecode. I simply pasted in some Java code in a block in between existing code and it _"just works"_. 

**What was I looking for in Janino?**

The way that `EXPR` currently works is that I'm using the internal/undocumented `javassist.compiler` api which is messy and very fragile. But its the only real option I have aside from making my own miniature compiler or finding a replacement. It does work more or less though. I can say _"When you see the name `stage` I want it to be treated as a local variable at index `2` with a type of `javafx.stage.Stage`"_. Then when it sees `stage` it will understand that it is `javafx.stage.Stage` and thus let me call methods on it like `setTitle(String)` as seen in the demo. When it compiles the expression loading the `stage` value becomes `ALOAD 2`. The variable index is controlled by me so that it integrates properly with the surrounding bytecode.

**How about building a fake method?**

The overall layout and formatting of Janino is much more to my preference, so if I can get this approach working I would be thrilled. I'll look into setting this up and get back with any questions should they arise.

The main item remaining with this approach is that I would like to avoid having to set up this method by specifying parameters with `java.lang.Class` instances. Reason being that a user of my program may not trust the application they are inspecting, so having to load the class into memory is not something I want to do. Since I have the `byte[]` of the class and can easily fetch field/method information it would be ideal being able to specify this information statically / manually. 

**The dreaded stack-maps...**

Thankfully I can ignore this part due to the usage of [ASM](https://asm.ow2.io/). This dreaded feature is abstracted away, so I don't have to deal with computing the complex stack interactions nor does the user have to be burdened with keeping them up-to-date. As long as their code isn't clearly illegal _(Like trying to pop off a value from an empty stack)_ ASM will do all the heavy lifting.

**Comment by aunkrig** [comment]
> The main item remaining with this approach is that I would like to avoid having to set up this method by specifying parameters with java.lang.Class instances. Reason being that a user of my program may not trust the application they are inspecting, so having to load the class into memory is not something I want to do. Since I have the byte[] of the class and can easily fetch field/method information it would be ideal being able to specify this information statically / manually.

Ah, Janino can help with that! Janino has a set of interfaces `IClass`, `IMethod`, etc. that are implemented either by a `ClassFileIClassLoader` (reflection), or by `ClassFileIClassLoader`, which reads bytecode .class files through a `ResourceFinderIClassLoader`.

Just out of curiosity: How does RECAF deal with the `StackMapTable` attribute, which must constantly be updated as the bytecode is moodified by the user?

**Comment by aunkrig** [comment]
At some point I ws considering to use ASM too, but didn't, so I had to implement the `StackMapTable` madness myself, which I now regret. That concept is really crazy!! E.g. if a LONG or DOUBLE element in the map goes out-of-scope, it is replaced with *two* placeholders, and the like... As someone said very truly: "StackMapTable destroys the beauty and simplicity of the Java bytecode." In reality, every JVM must support old .class files without StackMapTable anyway, so it can nevery rely on the "help" of that attribute. In practice, it can use the attribute only to *check* it for accuracy, which makes absolutely no sense.

Definitely one of the top ten "global very bad design decisions", like the backslash as the file separator in MS DOS-based operating systems...

**Comment by Col-E** [comment]
Going to be closing this for now while we look into this approach
