### ISSUE TITLE
Metaspace

### ISSUE THREAD

**Issue by mcrema** [janino-compiler/janino#162]
Hi
We have recently deployed an application to use Janino as an expression evaluator.  We are seeing some issues with out of memory for metaspace.  Is there any reason why using Janino as an expression evaluator could cause an increase in loaded classes?  We execute the following api.  We pass in a string expression that is evaluated to true or false.  This does get executed many times per user interaction and there are many interactions throughout the use of our application.   I know that is not a full description of how we use this but I was hoping it would trigger some ideas.  Thanks.

public Object processRule(Context context, Class[] classType, String[] ruleParam, Object[] arguments, String rule){
		Object res = null;
		//System.out.println("Process Rule: " + rule);
		try{
			IExpressionEvaluator ee = CompilerFactoryFactory.getDefaultCompilerFactory().newExpressionEvaluator();
			ee.setExpressionType(boolean.class);
			//set the attributes parameters with their class types
			ee.setParameters(ruleParam, classType);
			//pass in the rule 
			ee.cook(rule);
			// Evaluate expression with actual attribute parameter values.
			res = ee.evaluate(arguments);
		}catch(Exception exp){
                exp.printStackTrace();
                ContextUtil.abortTransaction(context);
		}
		return res;	
	}

**Comment by mcrema** [comment]
Thank you very much for the response.  I am very interested in your second suggestion because it is possible for me to gather the expressions.  I don’t remember seeing that in the documentation.  Can you point me to something that I can review?  Thanks.

**Comment by aunkrig** [comment]
http://janino-compiler.github.io/janino/apidocs/org/codehaus/commons/compiler/IExpressionEvaluator.html

, then search for „If you want to compile many expressions at the same time“.

**Comment by aunkrig** [comment]
No problem; just visit https://janino-compiler.github.io/janino/apidocs/org/codehaus/commons/compiler/IExpressionEvaluator.html and search for "If you want to compile many expressions at the same time".
