### ISSUE TITLE
Can you make your signing keys available.

### ISSUE THREAD

**Issue by rodwiddowson** [janino-compiler/janino#164]
Previous releases of this artifact were signed (on maven central) by this key
```
pub   rsa2048 2014-07-03 [SC]
      1EAD07B862D1D9ADD57BB4A358FE9D80369755E0
uid           [ unknown] Arno Unkrig <aunkrig@codehaus.org>
sub   rsa2048 2014-07-03 [E]
```
3.1.6 is signed by this key
```
pub   rsa2048 2016-07-26 [SC]
      37D75E23E6B6A6C573C9AE6FDFBF27530B637783
uid           [ unknown] Arno Unkrig <unkrig.arno@swm.de>
sig 3        DFBF27530B637783 2016-07-26  Arno Unkrig <unkrig.arno@swm.de>
sub   rsa2048 2016-07-26 [E]
sig          DFBF27530B637783 2016-07-26  Arno Unkrig <unkrig.arno@swm.de>
```

It would be extremely useful to people who check signatures on artifacts prior to using them (because of fears of supply chain attacks)  if you could publish your PGP_KEYS.txt file either on your website or as a file in this repository.

Failing which,  some checkable assertion that this key is valid would be appreciated

**Comment by rodwiddowson** [comment]
Thank @aunkrig That works a treat

**Comment by aunkrig** [comment]
Updated the home page accordingly - please review.

https://janino-compiler.github.io/janino/#security_integrity
