### ISSUE TITLE
Get generate method bytecode size

### ISSUE THREAD

**Issue by chaokunyang** [janino-compiler/janino#166]
I have a class generated by `org.codehaus.janino.Compiler`, the generated methods are too big to be inlined by java jit. Is there any way to get  the method bytecodes length from janino directly, so I can spilt the method into smaller methods? The generated class has more than one method, so I can't use `SimpleCompiler` to get the bytecode for method directly.

the class has following structure:
```

public final class Struct1648345735854Fury extends io.ray.fury.encoder.Generated.Generated {

    private java.lang.Class beanClass;
    private Fury fury;

    public Struct1648345735854Fury(Fury fury, Class classType) {
        super(fury, classType);
        this.fury = fury;
        initialize();
    }

    private void initialize() {
    }

    @Override public final void write(MemoryBuffer buffer, Object obj) {
        ...
    }

    @Override public final Object read(MemoryBuffer buffer) {
        ...
    }
}
```

**Comment by chaokunyang** [comment]
I can use javaassit for this, but I don't want to introduce another dependency:
```
try (InputStream is = ForwardSerializer.class.getResourceAsStream("ForwardSerializer.class")) {
      ClassFile cf = new ClassFile(new DataInputStream(is));
      for (Object miO : cf.getMethods()) {
        MethodInfo mi = (MethodInfo) miO;
        CodeAttribute ca = mi.getCodeAttribute();
        if (ca == null) continue; // abstract or native
        int bLen = ca.getCode().length;
        System.out.println(mi.getName() + " " + mi.getDescriptor() + ", " + bLen + " bytes");
      }
    }
```

**Comment by aunkrig** [comment]
Hey Shawn,

Janino does not have an API to get the sizes of the code attributes as they are generated by the `UnitCompiler`.

While it would be possible to implement such an API, I believe it is much easier and also much more portable to examine the .class files *after* they have been generated. There are many libraries which provide that feature. You could as well use Janino's own utiltity method `org.codehaus.janino.util.ClassFile.ClassFile(InputStream)`.

Does that help?

CU Arno

**Comment by aunkrig** [comment]
No wait, I found a way: You extend `UnitCompiler`, and override `storeClassFile()`! Iterate `ClassFile.methodInfos`, then their `attributes`, and check which is the `CodeAttribute`, and check its `code.length` (which currently is `private`, unfortunately).

BTW, `SimpleCompiler`is *not* limited to one method, nor one class; it is limited to one *compilation unit*. From what I understand from your description, you want to compile only CU, right?

One more thing: Are you sure that it is defintely the byte code size that determines whether the JIT inlines a method? Even if, it would be extremely JVM-dependant to optimize like that.

**Comment by chaokunyang** [comment]
Thanks for your quick reply. I finally got method sizes by following code:
```
public static CodeStats getClassStats(byte[] classBytes) {
    try {
      ClassFile classFile = new ClassFile(new ByteArrayInputStream(classBytes));
      int constPoolSize = classFile.getConstantPoolSize();
      Class<?> codeAttrClass =
          Compiler.class
              .getClassLoader()
              .loadClass("org.codehaus.janino.util.ClassFile$CodeAttribute");
      Field codeAttrField = codeAttrClass.getDeclaredField("code");
      codeAttrField.setAccessible(true);
      Map<String, Integer> methodSizes = new LinkedHashMap<>();
      classFile.methodInfos.stream()
          .flatMap(
              m ->
                  Arrays.stream(m.getAttributes())
                      .filter(attr -> attr.getClass() == codeAttrClass)
                      .map(
                          attr -> {
                            try {
                              Object codeAttr = codeAttrField.get(attr);
                              int length = ((byte[]) codeAttr).length;
                              if (length > CodeGenerator.DEFAULT_JVM_HUGE_METHOD_LIMIT) {
                                LOG.info(
                                    "Generated method too long to be JIT compiled:"
                                        + " class {} method {} size {}",
                                    classFile.getThisClassName(),
                                    m.getName(),
                                    length);
                              }
                              return Tuple2.of(m.getName(), length);
                            } catch (IllegalAccessException e) {
                              throw new RuntimeException(e);
                            }
                          }))
          .sorted(Comparator.comparingInt(a -> -a.f1))
          .forEach(e -> methodSizes.put(e.f0, e.f1));
      return new CodeStats(methodSizes, constPoolSize);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
```

**Comment by chaokunyang** [comment]
I run the generated code and there many logs like ` hot method too big`. If I don't break the codes into small methods, the users of my library won't get the enough speed up out-of-box without tuning jit flags.

**Comment by aunkrig** [comment]
Hey Shawn,

I added `GithubIssuesTest.testIssue166()` which demonstrates how to do it. You also need to update to the HEAD because I had to make some code changes too.

Please test!

**Comment by chaokunyang** [comment]
Thanks, will test ASAP.
