### ISSUE TITLE
Problems with varargs and inheritance

### ISSUE THREAD

**Issue by BruecklHotvolleys** [janino-compiler/janino#169]
Hi,
I have created a drawing tool to create (animated) images (e.g. matchstick men) with script.

This is how I create these images - this is a line...
````
line(0, 0, 100, 100)
  .thickness(5)
  //.dashed(1f, 10f)
  .roundedLines()
  //.xx(1, 2, 3)
;
````

The base class is ActorImpl with interface Actor defining following methods:
````
Actor dashed(float... dashed);
Actor xx(int... test);
````

In class LineImpl (with interface Line) they are overwritten:
````
@Override
Line dashed(float... dashed);
@Override
Line xx(int... test);
````

Overwriting seems to be necessary to call other methods of Line(Impl) after this call that are only declared in Line.
(Wouldn't be necessary if I'm using beanshell, but janino has some advantages.)

I get following error if I call xx:
````
Assignment conversion not possible from type "int" to type "int[]"
org.codehaus.commons.compiler.CompileException: Line 130, Column 4: Assignment conversion not possible from type "int" to type "int[]"
````

And a similar error for dashed(...)
````
Assignment conversion not possible from type "float" to type "float[]"
org.codehaus.commons.compiler.CompileException: Line 128, Column 4: Assignment conversion not possible from type "float" to type "float[]"
````

Other methods work like expected, so I think the problem is overwriting the methods with varargs.
If I do not overwrite them, then its working, but as I said above its not possible to call Line methods after this call which will be necessary for other situations.

Thanks for helping.

**Comment by aunkrig** [comment]
That's strange...

Can you please implement a minimal test case, in class `org.codehaus.commons.compiler.tests.ReportedBugsTest`, like this:

    @Test public void
    testIssue172() {
        assertCompilationUnitCookable(
            "(your code here)\n"
        );
    }

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Which Janino version are you using?
Added a test case for this issue (`org.codehaus.commons.compiler.tests.ReportedBugsTest.testIssue169()`):

    @Test public void
    testIssue169() throws Exception {
        this.assertCompilationUnitMainExecutable((
            ""
            + "public interface Actor {\n"
            + "    Actor dashed(float... dashed);\n"
            + "    Actor xx(int... test);\n"
            + "}\n"
            + "\n"
            + "public class ActorImpl implements Actor {\n"
            + "    @Override public Actor dashed(float... dashed) { return this; }\n"
            + "    @Override public Actor xx(int... test)         { return this; }\n"
            + "}\n"
            + "\n"
            + "public class Main {\n"
            + "    public static void main() {\n"
            + "        new ActorImpl().dashed(1f, 10f).xx(1, 2, 3);\n"
            + "\n"
            + "        ActorImpl a = new ActorImpl();\n"
            + "        a.dashed(1f, 10f).xx(1, 2, 3);\n"
            + "    }\n"
            + "}\n"
        ), "Main");
    }

Can't reproduce the problem (test case succeeds).

If updating to a newer version (3.1.11+) doesn't help, feel free to re-open this issue, or submit another one.

**Comment by volleybase** [comment]
Have tested it now with 3.1.12 (and 3.1.9).
varargs are working as expected (at least in test and with 3.1.12).
I'm still trying to create a smaller test case for the inheritance problem - that problem is still active...
