### ISSUE TITLE
Need solution for running in Google App Engine

### ISSUE THREAD

**Issue by jpmunson** [janino-compiler/janino#17]
This code causes an error in Janino v3.0.6 when running on Google AppEngine (although not in their development server):
```
import java.util.Scanner;
public class T1
{
    public static void main(String[] args)
    {
        Scanner scnr = new Scanner(System.in);
    }
}
```
The error is this:

`Compiling "T1": "findIClass()" returned "Lcom/google/apphosting/runtime/security/shared/stub/java/nio/file/Path;" instead of "Ljava/nio/file/Path;"`

The source seems to be this code in `org.codehaus.janino.IClassLoader` (lines 305-313):
```
        if (!result.getDescriptor().equalsIgnoreCase(fieldDescriptor)) {
            throw new JaninoRuntimeException(
                "\"findIClass()\" returned \""
                + result.getDescriptor()
                + "\" instead of \""
                + fieldDescriptor
                + "\""
            );
        }
```
Would it be possible to have some kind of compile-time or run-time switch that would go around this code when compiling for, or running in, Google App Engine?

Thanks,

Jon

**Comment by aunkrig** [comment]
Hello Jon,

thank you for your bug report. This problem appears to be very specific for the GOOGLE APP ENGINE environment, which I don't have available, and, unfortunately, I will not have the time to get aquainted with it.

However I still want to help you, so my first diagnosis is that GAE uses its own ClassLoader, which, strangely, when told to load class "java.nio.file.Path", loads and returns a DIFFERENT class, namely "com.google.apphosting.runtime.security.shared.stub.java.nio.file.Path". That would cleary break the contract of "ClassLoader.findClass()", and I wonder how this would ever work!?

Could you please analyze what happens in the call to "findIClass()" in line 298 and find out whether I'm right?


CU

Arno

**Comment by jpmunson** [comment]
Hi Arno,

Thanks for considering this. Yes, that’s what is happening. I put in a bunch of trace statements and this is what I learned:

1. loadIClass is called with fieldDescriptor = "Ljava/nio/file/Path;”

2. It does not find it in loadedIClasses so calls findIClass

3. findIClass gets the class from the Google class loader, wraps it in an IClass and then calls defineIClass

4. defineIClass looks in loadedIClasses, doesn’t find it, so stores it in loadedIClasses with the key “Lcom/google/apphosting/runtime/security/shared/stub/java/nio/file/Path;” (returned by iClass.getDescriptor())

5. defineIClass returns, findIClass returns, and then checks that the descriptor of the class it asked for matches the descriptor of the result. If it doesn’t it throws the exception I wrote to you about. For my investigation I commented out the code for this check.

6. loadIClass is called a second time with fieldDescriptor "Ljava/nio/file/Path;”

7. It does not find it in loadedIClasses—with this key---so calls findIClass.

8. findIClass gets the class from the Google class loader, wraps it in an IClass and then calls defineIClass

9. defineIClass looks in loadedIClasses, finds it, then checks that the IClass in loadedIClasses is the same object as what it was about to put in.

And this is where a second exception occurs. I can’t give you line numbers because mine are off now, but this is the code (in IClassLoader.defineIClass):

            if (loadedIClass == iClass) return;
            throw new JaninoRuntimeException("Non-identical definition of IClass \"" + descriptor + "\"");

The reason loadedIClass is not equal to iClass is because the IClass wrapper is created twice, once in step 3 and again in step 8. The reason findIClass is called twice for the same class is because loadIClass is looking for the class in loadedIClasses with the key "Ljava/nio/file/Path;”, but it is eventually stored in loadedIClasses with the key “Lcom/google/apphosting/runtime/security/shared/stub/java/nio/file/Path;”.

Here is my local solution:

I modified the constructor of ReflectionIClass to take a third parameter, the descriptor to use for the instance.
I modified the getDescriptor2() method to return this descriptor rather than a string based on the class name.

With these modifications, the IClass returned for "Ljava/nio/file/Path;” is cached with that key, so the exceptions don’t happen.

Let me know if you need any clarifications. I’d be glad to do a git push if that makes it easier for you.

—Jon

**Comment by aunkrig** [comment]
Hi Jon,

I'd appreciate a PUSH!


CU

Arno

**Comment by aunkrig** [comment]
AYT?

**Comment by jpmunson** [comment]
Hi Arno,

Yes, I’m here. Update: I’m still running the app on App Engine, but have split off Java execution onto a container, so am using the OpenJDK compiler.

—Jon
