### ISSUE TITLE
building from sources?

### ISSUE THREAD

**Issue by hardlyb** [janino-compiler/janino#171]
I can't figure out how to rebuild the jars from sources. What's the trick?

**Comment by yuripourre** [comment]
```
cd janino
mvn build
```

Does that work?

**Comment by hardlyb** [comment]
Not for me. In the root directory for the git repo, which I have in
~/work/janino/, there is no pom.xml file. If I go to the janino
subdirectory, I get this:






















*/Users/hsexton/work/janino/janino: mvn build[INFO] Scanning for
projects...[INFO] Inspecting build with total of 1 modules...[INFO]
Installing Nexus Staging features:[INFO]   ... total of 1 executions of
maven-deploy-plugin replaced with nexus-staging-maven-plugin[INFO] [INFO]
---------------------< org.codehaus.janino:janino
>---------------------[INFO] Building janino 3.1.8-SNAPSHOT[INFO]
--------------------------------[ jar
]---------------------------------[INFO]
------------------------------------------------------------------------[INFO]
BUILD FAILURE[INFO]
------------------------------------------------------------------------[INFO]
Total time:  1.035 s[INFO] Finished at: 2022-07-06T22:42:16-05:00[INFO]
------------------------------------------------------------------------[ERROR]
Unknown lifecycle phase "build". You must specify a valid lifecycle phase
or a goal in the format <plugin-prefix>:<goal> or
<plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available
lifecycle phases are: validate, initialize, generate-sources,
process-sources, generate-resources, process-resources, compile,
process-classes, generate-test-sources, process-test-sources,
generate-test-resources, process-test-resources, test-compile,
process-test-classes, test, prepare-package, package, pre-integration-test,
integration-test, post-integration-test, verify, install, deploy,
pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. ->
[Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run
Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable
full debug logging.[ERROR] [ERROR] For more information about the errors
and possible solutions, please read the following articles:[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
<http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException>*

I tried compile and got this:
























*/Users/hsexton/work/janino/janino: mvn compile[INFO] Scanning for
projects...[INFO] Inspecting build with total of 1 modules...[INFO]
Installing Nexus Staging features:[INFO]   ... total of 1 executions of
maven-deploy-plugin replaced with nexus-staging-maven-plugin[INFO] [INFO]
---------------------< org.codehaus.janino:janino
>---------------------[INFO] Building janino 3.1.8-SNAPSHOT[INFO]
--------------------------------[ jar
]---------------------------------[WARNING] The POM for
org.codehaus.janino:commons-compiler:jar:3.1.8-SNAPSHOT is missing, no
dependency information available[INFO]
------------------------------------------------------------------------[INFO]
BUILD FAILURE[INFO]
------------------------------------------------------------------------[INFO]
Total time:  1.128 s[INFO] Finished at: 2022-07-06T22:46:47-05:00[INFO]
------------------------------------------------------------------------[ERROR]
Failed to execute goal on project janino: Could not resolve dependencies
for project org.codehaus.janino:janino:jar:3.1.8-SNAPSHOT: Could not find
artifact org.codehaus.janino:commons-compiler:jar:3.1.8-SNAPSHOT -> [Help
1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven
with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full
debug logging.[ERROR] [ERROR] For more information about the errors and
possible solutions, please read the following articles:[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
<http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException>*

**Comment by aunkrig** [comment]
Honestly, I cannot help with your Maven problem. Janino is just an ordinary multi-module Maven project and should compile easily.

You need to check out all five modules `janino-parent`, `janino`, `commons-compiler`, `commons-compiler-jdk` and `commons-compiler-tests`. Then you would build the `janino-parent` module, and it will build the other four automatically.

Does this help?
