### ISSUE TITLE
"String s = System.out.println();" throws an InternalCompilerException

### ISSUE THREAD

**Issue by ZZKILLER** [janino-compiler/janino#176]
When UnitCompiler goes to assignment that assigns a return type void method invoke to a non primitive variable.It crashes on method 'org.codehaus.janino.UnitCompiler.tryAssignmentConversion' with an InternalCompileException instead of throwing an CompileException. Please fix it, Thanks.
Sry my English is bad.

**Comment by aunkrig** [comment]
`UnitCompiler` had problems differentiating between the type of a `void` method, and the type of the `null` literal. Added a new constant `IClass.NULL` for the latter.

Please test.

**Comment by ZZKILLER** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arno ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 晚上10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [janino-compiler/janino] &quot;String s = System.out.println();&quot; throws an InternalCompilerException (Issue #176)





 
UnitCompiler had problems differentiating between the type of a void method, and the type of the null literal. Added a new constant IClass.NULL for the latter.
 
Please test.
