### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.MF

### ISSUE THREAD

**Issue by ceki** [janino-compiler/janino#183]
Given that Janino artifacts are not modularized, it would help if you could set `Automatic-Module-Name` property in  MANIFEST.MF.

I would suggest the following names:

|artifact|suggested Automatic-Module-Name value|
|-------|---------------------------------|
|org.codehaus.janino:commons-compiler|org.codehaus.janino.commons.compiler|
|org.codehaus.janino:janino|org.codehaus.janino.janino|

These names can be added to your pom.xml as follows:

```<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <archive combine.children="append">
                <manifestEntries>
                  <Automatic-Module-Name>org.codehaus.janino.janino</Automatic-Module-Name>
                </manifestEntries>
              </archive>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

This issue is a blocker for the logback project.

SLF4J 1.7.x series added  Automatic-Module-Name  entries a while back. See [slf4j PR 184](https://github.com/qos-ch/slf4j/pull/184/)

**Comment by aunkrig** [comment]
Hey Ceki,

do don't understand a lot about modules... could that entry in the manifest have negative consequences for other users?


CU Arno

**Comment by ceki** [comment]
Hi @aunkrig,

I doubt adding Auto-Module-Name entries will have a  negative effect. When  Auto-Module-Name entries were added to SLF4J 1.7.x series several years, ago no one complained.

**Comment by ceki** [comment]
Patch

```
diff --git a/commons-compiler/pom.xml b/commons-compiler/pom.xml
index 2b4436b6..61b3ad99 100644
--- a/commons-compiler/pom.xml
+++ b/commons-compiler/pom.xml
@@ -17,6 +17,18 @@

   <build>
     <plugins>
+      <plugin>
+        <artifactId>maven-jar-plugin</artifactId>
+        <version>3.0.2</version>
+        <configuration>
+          <archive>
+             <manifestEntries combine.children="append">
+                  <Automatic-Module-Name>org.codehaus.janino.commons.compiler</Automatic-Module-Name>
+             </manifestEntries>
+          </archive>
+        </configuration>
+      </plugin>
+
       <plugin>
         <groupId>org.apache.felix</groupId>
         <artifactId>maven-bundle-plugin</artifactId>
diff --git a/janino/pom.xml b/janino/pom.xml
index 0a66697f..cb74c5e7 100644
--- a/janino/pom.xml
+++ b/janino/pom.xml
@@ -46,6 +46,18 @@

   <build>
     <plugins>
+      <plugin>
+        <artifactId>maven-jar-plugin</artifactId>
+        <version>3.0.2</version>
+        <configuration>
+          <archive>
+             <manifestEntries combine.children="append">
+                  <Automatic-Module-Name>org.codehaus.janino.janino</Automatic-Module-Name>
+             </manifestEntries>
+          </archive>
+        </configuration>
+      </plugin>
+
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
```

**Comment by aunkrig** [comment]
Hey Ceki,

I looked into that and have the following questians:

1. `commons-compiler-jdk` should also have an automatic-module-name, right?
2. Is it really useful to give every maven module (`janino`, `commons-compiler`and maybe `commons-compiler-jdk`) an individual (Java) module name, as you propose? I.e. why would one open the maven modules individually for, say, `log4j`? Or is it just good style to have distinct (Java) module names for each `.jar` file?

CU Arno

**Comment by ceki** [comment]
1) yes. commons-compiler-jdk should also have an automatic-module-name
2) Non jigsaw/JPMS artifacts are **already** automatically assigned a module name. For example, janino.jar is already assigned the module name "janino" and commons-compiler.jar the name "commons-compiler". By setting the name via `Auto-Module-Name`, you are establishing _today_ a contract for the names your modules will have in the _future_, when and if you decide to  jigsaw/JPMS modularize them. Otherwise, users depending on janino will have to change their module-info declarations from "requires janino" (janino is the current module name) to "requires "some.new.name.for.janino".

Setting  a `Auto-Module-Name` in your artifacts is a very small step in the direction of   jigsaw/JPMS modularization.

**Comment by aunkrig** [comment]
Ok, I added the manifest entry to all four modules:
```
$ zzgrep --include '***!META-INF/MANIFEST.MF' Automatic */target/*.jar
commons-compiler\target\commons-compiler-3.1.10-SNAPSHOT.jar!META-INF/MANIFEST.MF:Automatic-Module-Name: org.codehaus.commons.compiler
commons-compiler-jdk\target\commons-compiler-jdk-3.1.10-SNAPSHOT.jar!META-INF/MANIFEST.MF:Automatic-Module-Name: org.codehaus.commons.compiler.jdk
commons-compiler-tests\target\commons-compiler-tests-3.1.10-SNAPSHOT.jar!META-INF/MANIFEST.MF:Automatic-Module-Name: org.codehaus.commons.compiler.tests
janino\target\janino-3.1.10-SNAPSHOT.jar!META-INF/MANIFEST.MF:Automatic-Module-Name: org.codehaus.janino
$
```
Is that totally correct? Please check carefully.

**Comment by ceki** [comment]
@aunkrig  It seems to me that the names should be prefixed by "org.codehaus.**janino**" and not just "org.codehaus".

**Comment by aunkrig** [comment]
I read that the module name should be equal to the "main package" of the module -- that would be *without* an additional ".janino." infix, right?

**Comment by ceki** [comment]
Yes. You are right. I somehow missed that the packages contained "org.codehaus.janino:commons-compiler" artifact did not have **janino** in their middle. 

In JMPS/Jigsaw modularized applications, it is not possible for two artifacts (jar files) to duplicate a given package. This rule is enforced by the JVM at both compile and runtime. It is also true that the JVM will not allow two artifacts to have the same module name. 

To cut a long story short, as the likelihood of collision under the org.codehaus stem is very low, both "org.codehaus.janino" and "org.codehaus" would work just fine. If I had to choose, I'd have a slight preference for "org.codehaus.janino".
