### ISSUE TITLE
Get bytecode after compile

### ISSUE THREAD

**Issue by YuvalPyramid** [janino-compiler/janino#19]
can i separate the compile and load, and get the bytecode after compile process?

**Comment by aunkrig** [comment]
Hello Yuval,

yes,  I can show you how.

Can you please provide a bit more context information, e.g. whether you want to compile expressions, scripts, class bodies and/compilation units?

And what do you want to do with the bytecode?

CU Arno

**Comment by YuvalPyramid** [comment]
hey,
 Thank you for your attention.
i need to compile a class with some dynamic functions that i get from the user.
then i take the bytecode and save it to the data base.
afterwards, in some cases i need to run this bytecode on my server.

**Comment by aunkrig** [comment]
I added a test case `GithubIssuesTest` that demonstrates how it can be done. Please check if that is what you need!

**Comment by aunkrig** [comment]
Closed due to lack of activity.

**Comment by inizen** [comment]
Hi Arno:

Is there a way to get the compiled bytecode from SimpleCompiler? I want to compile dynamic classes that inherit from app classes, but store the resultant bytecode in a database for later speedy loading.

Regards,
Martin
