### ISSUE TITLE
Assignment conversion not possible from type "java.lang.Object"

### ISSUE THREAD

**Issue by shevchuk** [janino-compiler/janino#192]
janino "3.1.9"
There is a problem with compiling a file that has an `Enum` like that:

```
package p1234;
import java.io.IOException;
import java.util.Map;
import java.util.HashMap;
import java.util.Arrays;

public class IcmpPacket extends KaitaiStruct {
    public static IcmpPacket fromFile(String fileName) throws IOException {
        return new IcmpPacket(9999);
    }

    public enum IcmpTypeEnum {
        ECHO_REPLY(0),
        DESTINATION_UNREACHABLE(3),
        SOURCE_QUENCH(4),
        REDIRECT(5),
        ECHO(8),
        TIME_EXCEEDED(11);

        private final long id;
        IcmpTypeEnum(long id) { this.id = id; }
        public long id() { return id; }
        private static final Map<Long, IcmpTypeEnum> byId = new HashMap<Long, IcmpTypeEnum>(6);
        static {
            for (IcmpTypeEnum e : IcmpTypeEnum.values())
                byId.put(e.id(), e);
        }
        public static IcmpTypeEnum byId(long id) { return byId.get(id); }
    }

    public IcmpPacket(Long _io) {
        this(_io, null, null);
    }
}
```

It raises the error:

```
Execution error (CompileException) at org.codehaus.janino.UnitCompiler/compileError (UnitCompiler.java:13014).
File 'src/p1234/IcmpPacket.java', Line 34, Column 52: Assignment conversion not possible from type "java.lang.Object" to type "p1234.IcmpPacket$IcmpTypeEnum"
```

**Comment by aunkrig** [comment]
Hey Mike,

you've run into a limitation of Janino described [here](https://janino-compiler.github.io/janino/#limitations): Janino parses type arguments, but then ignores them. So effectively your

    private static final Map<Long, IcmpTypeEnum> byId = new HashMap<Long, IcmpTypeEnum>(6);
is

    private static final Map<Object, Object> byId = new HashMap<Object, Object>(6);
As a result,

    byId.get(id);
produces a `java.lang.Object`, which is not "assignment-compatible" with the method's return type.

The simple workaround is to add an explicit cast operation:

    return (IcmpTypeEnum) byId.get(id);

**Comment by shevchuk** [comment]
Hello @aunkrig ! Thanks a lot for your detailed answer and I can confirm that this fixes the issue. Unfortunately this is the code generated by another library (kaitai) so I guess I need to solve it there somehow.
