### ISSUE TITLE
Evaluate method is ambiguous

### ISSUE THREAD

**Issue by caithesi** [janino-compiler/janino#204]
I am using java 17, janino version 3.1.9
When i try to call evaluate method with at least 1 parameter, i got : 
"reference to evaluate is ambiguous
  both method evaluate(java.lang.Object...) in org.codehaus.janino.ExpressionEvaluator and method evaluate(int,java.lang.Object...) in org.codehaus.janino.ExpressionEvaluator match"
for example: 

 This will throw error:

        var stringExpression = "x + y + 10 + 100";
        var ee = new ExpressionEvaluator(
                stringExpression,
                long.class,
                new String[]{"x", "y"},
                new Class[]{int.class, int.class});
        var res = t.evaluate(1, 2);

Is this a bug or i did something wrong?
Thank you.

**Comment by aunkrig** [comment]
Fixed it; please test.

> **Notice:** In version 3.1.8, the _arguments_ parameter was changed from `Object[]` to `Object...`, which turned out to be a really bad decision because it caused a very ugly invocation ambiguity with `evaluate(int, Object[])`. Thus, with version 3.1.10, the parameter was changed back to `Object[]`.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.
