### ISSUE TITLE
spark compilation failed with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by igreenfield** [janino-compiler/janino#208]
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at org.codehaus.janino.UnitCompiler.updateLocalVariableInCurrentStackMap(UnitCompiler.java:13568) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.store(UnitCompiler.java:12758) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.store(UnitCompiler.java:12730) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2742) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.access$2700(UnitCompiler.java:236) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$6.visitLocalVariableDeclarationStatement(UnitCompiler.java:1589) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$6.visitLocalVariableDeclarationStatement(UnitCompiler.java:1575) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.Java$LocalVariableDeclarationStatement.accept(Java.java:3842) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1575) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1661) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3658) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3329) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1447) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1420) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:829) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1026) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.access$700(UnitCompiler.java:236) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$3.visitMemberClassDeclaration(UnitCompiler.java:425) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$3.visitMemberClassDeclaration(UnitCompiler.java:418) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.Java$MemberClassDeclaration.accept(Java.java:1533) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:418) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compileDeclaredMemberTypes(UnitCompiler.java:1397) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:864) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:442) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:236) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:422) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:418) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1688) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:418) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:392) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:236) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:363) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:361) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.Java$CompilationUnit.accept(Java.java:371) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:361) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:264) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:294) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:288) ~[janino-3.1.9.jar:?]
	at org.codehaus.janino.ClassBodyEvaluator.cook(ClassBodyEvaluator.java:267) ~[janino-3.1.9.jar:?]
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:82) ~[commons-compiler-3.1.9.jar:?]
	at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.org$apache$spark$sql$catalyst$expressions$codegen$CodeGenerator$$doCompile(CodeGenerator.scala:1512)

**Comment by aunkrig** [comment]
Hey Izek,

that is a bit too little information to reproduce the problem... what code are you trying to compile? Please provide a small, runnable example.

CU Arno

**Comment by aunkrig** [comment]
Ping.

**Comment by igreenfield** [comment]
public java.lang.Object generate(Object[] refs) {
return new SpecificMutableProjection(refs);
}

class SpecificMutableProjection extends org.apache.spark.sql.catalyst.expressions.codegen.BaseMutableProjection {

private Object[] refs;
private InternalRow mutableRow;
private boolean isN_0_0;
private boolean isN_3_0;
private boolean isN_6_0;
private boolean isN_9_0;
private boolean isN_12_0;
private boolean isN_15_0;
private boolean isN_18_0;
private boolean isN_21_0;
private boolean isN_24_0;
private boolean isN_27_0;
private boolean isN_30_0;
private boolean isN_34_0;
private boolean isN_39_0;
private boolean isN_44_0;
private boolean isN_49_0;
private boolean isN_55_0;
private boolean isN_60_0;
private boolean isN_64_0;
private boolean isN_67_0;
private boolean isN_70_0;
private boolean isN_73_0;
private long value_0;
private boolean isNull_0;
private boolean isNull_1;
private double value_1;
private double value_2;
private double value_3;
private long value_4;
private double value_5;
private double value_6;
private boolean isNull_2;
private boolean isNull_3;
private boolean isNull_4;
private UTF8String[] mStArr_0 = new UTF8String[14];

public SpecificMutableProjection(Object[] refs) {
this.refs = refs;
mutableRow = new org.apache.spark.sql.catalyst.expressions.GenericInternalRow(21);


}

public void initialize(int partitionIndex) {

}

public org.apache.spark.sql.catalyst.expressions.codegen.BaseMutableProjection target(InternalRow row) {
mutableRow = row;
return this;
}

/* Provide immutable access to the last projected row. */
public InternalRow currentValue() {
return (InternalRow) mutableRow;
}

public java.lang.Object apply(java.lang.Object _i) {
InternalRow i = (InternalRow) _i;

apply_0_0(i);
apply_0_1(i);
apply_0_2(i);
apply_0_3(i);
apply_0_4(i);
apply_0_5(i);
apply_0_6(i);
apply_0_7(i);
apply_0_8(i);
apply_0_9(i);
apply_0_10(i);
// copy all the results into MutableRow
apply_1_0(i);
apply_1_1(i);
return mutableRow;
}


private void apply_0_4(InternalRow i) {

isN_24_0 = true;
UTF8String val_24 = null;

boolean isN_25 = i.isNullAt(8);
UTF8String val_25 = isN_25 ?
null : (i.getUTF8String(8));

if (!isN_25 && (isN_24_0 ||
(val_25.compare(val_24)) > 0)) {
isN_24_0 = false;
val_24 = val_25;
}


UTF8String val_26 = i.getUTF8String(30);

if (!false && (isN_24_0 ||
(val_26.compare(val_24)) > 0)) {
isN_24_0 = false;
val_24 = val_26;
}
mStArr_0[7] = val_24;

isN_27_0 = true;
UTF8String val_27 = null;

boolean isN_28 = i.isNullAt(9);
UTF8String val_28 = isN_28 ?
null : (i.getUTF8String(9));

if (!isN_28 && (isN_27_0 ||
(val_28.compare(val_27)) > 0)) {
isN_27_0 = false;
val_27 = val_28;
}


boolean isN_29 = i.isNullAt(31);
UTF8String val_29 = isN_29 ?
null : (i.getUTF8String(31));

if (!isN_29 && (isN_27_0 ||
(val_29.compare(val_27)) > 0)) {
isN_27_0 = false;
val_27 = val_29;
}
isNull_0 = isN_27_0;
mStArr_0[8] = val_27;

}


private void apply_0_7(InternalRow i) {

isN_49_0 = true;
long val_49 = -1L;
do {

boolean isN_50 = i.isNullAt(14);
long val_50 = isN_50 ?
-1L : (i.getLong(14));
if (!isN_50) {
isN_49_0 = false;
val_49 = val_50;
continue;
}


isN_49_0 = false;
val_49 = 0L;
continue;

} while (false);
int val_53 = i.getInt(36);
boolean isN_52 = false;
long val_52 = -1L;
if (!false) {
val_52 = (long) val_53;
}
long val_48 = -1L;

val_48 = val_49 + val_52;
value_4 = val_48;

isN_55_0 = true;
double val_55 = -1.0;
do {

boolean isN_56 = i.isNullAt(15);
double val_56 = isN_56 ?
-1.0 : (i.getDouble(15));
if (!isN_56) {
isN_55_0 = false;
val_55 = val_56;
continue;
}


isN_55_0 = false;
val_55 = 0.0D;
continue;

} while (false);
double val_58 = i.getDouble(37);
double val_54 = -1.0;

val_54 = val_55 + val_58;
value_5 = val_54;

}


private void apply_0_1(InternalRow i) {

isN_6_0 = true;
UTF8String val_6 = null;

boolean isN_7 = i.isNullAt(2);
UTF8String val_7 = isN_7 ?
null : (i.getUTF8String(2));

if (!isN_7 && (isN_6_0 ||
(val_7.compare(val_6)) > 0)) {
isN_6_0 = false;
val_6 = val_7;
}


UTF8String val_8 = i.getUTF8String(24);

if (!false && (isN_6_0 ||
(val_8.compare(val_6)) > 0)) {
isN_6_0 = false;
val_6 = val_8;
}
mStArr_0[1] = val_6;

isN_9_0 = true;
UTF8String val_9 = null;

boolean isN_10 = i.isNullAt(3);
UTF8String val_10 = isN_10 ?
null : (i.getUTF8String(3));

if (!isN_10 && (isN_9_0 ||
(val_10.compare(val_9)) > 0)) {
isN_9_0 = false;
val_9 = val_10;
}


UTF8String val_11 = i.getUTF8String(25);

if (!false && (isN_9_0 ||
(val_11.compare(val_9)) > 0)) {
isN_9_0 = false;
val_9 = val_11;
}
mStArr_0[2] = val_9;

}


private void apply_1_0(InternalRow i) {
mutableRow.update(0, mStArr_0[0].copy());mutableRow.setLong(1, value_0);mutableRow.update(2, mStArr_0[1].copy());mutableRow.update(3, mStArr_0[2].copy());mutableRow.update(4, mStArr_0[3].copy());mutableRow.update(5, mStArr_0[4].copy());mutableRow.update(6, mStArr_0[5].copy());mutableRow.update(7, mStArr_0[6].copy());mutableRow.update(8, mStArr_0[7].copy());
if (!isNull_0) {
mutableRow.update(9, mStArr_0[8].copy());
} else {
mutableRow.setNullAt(9);
}

if (!isNull_1) {
mutableRow.update(10, mStArr_0[9].copy());
} else {
mutableRow.setNullAt(10);
}
mutableRow.setDouble(11, value_1);mutableRow.setDouble(12, value_2);mutableRow.setDouble(13, value_3);mutableRow.setLong(14, value_4);mutableRow.setDouble(15, value_5);mutableRow.setDouble(16, value_6);mutableRow.update(17, mStArr_0[10].copy());
if (!isNull_2) {
mutableRow.update(18, mStArr_0[11].copy());
} else {
mutableRow.setNullAt(18);
}

}


private void apply_0_3(InternalRow i) {

isN_18_0 = true;
UTF8String val_18 = null;

boolean isN_19 = i.isNullAt(6);
UTF8String val_19 = isN_19 ?
null : (i.getUTF8String(6));

if (!isN_19 && (isN_18_0 ||
(val_19.compare(val_18)) > 0)) {
isN_18_0 = false;
val_18 = val_19;
}


UTF8String val_20 = i.getUTF8String(28);

if (!false && (isN_18_0 ||
(val_20.compare(val_18)) > 0)) {
isN_18_0 = false;
val_18 = val_20;
}
mStArr_0[5] = val_18;

isN_21_0 = true;
UTF8String val_21 = null;

boolean isN_22 = i.isNullAt(7);
UTF8String val_22 = isN_22 ?
null : (i.getUTF8String(7));

if (!isN_22 && (isN_21_0 ||
(val_22.compare(val_21)) > 0)) {
isN_21_0 = false;
val_21 = val_22;
}


UTF8String val_23 = i.getUTF8String(29);

if (!false && (isN_21_0 ||
(val_23.compare(val_21)) > 0)) {
isN_21_0 = false;
val_21 = val_23;
}
mStArr_0[6] = val_21;

}


private void apply_0_10(InternalRow i) {

isN_73_0 = true;
UTF8String val_73 = null;

boolean isN_74 = i.isNullAt(20);
UTF8String val_74 = isN_74 ?
null : (i.getUTF8String(20));

if (!isN_74 && (isN_73_0 ||
(val_73.compare(val_74)) > 0)) {
isN_73_0 = false;
val_73 = val_74;
}


boolean isN_75 = i.isNullAt(42);
UTF8String val_75 = isN_75 ?
null : (i.getUTF8String(42));

if (!isN_75 && (isN_73_0 ||
(val_73.compare(val_75)) > 0)) {
isN_73_0 = false;
val_73 = val_75;
}
isNull_4 = isN_73_0;
mStArr_0[13] = val_73;

}


private void apply_0_6(InternalRow i) {

isN_39_0 = true;
double val_39 = -1.0;
do {

boolean isN_40 = i.isNullAt(12);
double val_40 = isN_40 ?
-1.0 : (i.getDouble(12));
if (!isN_40) {
isN_39_0 = false;
val_39 = val_40;
continue;
}


isN_39_0 = false;
val_39 = 0.0D;
continue;

} while (false);
double val_42 = i.getDouble(34);
double val_38 = -1.0;

val_38 = val_39 + val_42;
value_2 = val_38;

isN_44_0 = true;
double val_44 = -1.0;
do {

boolean isN_45 = i.isNullAt(13);
double val_45 = isN_45 ?
-1.0 : (i.getDouble(13));
if (!isN_45) {
isN_44_0 = false;
val_44 = val_45;
continue;
}


isN_44_0 = false;
val_44 = 0.0D;
continue;

} while (false);
double val_47 = i.getDouble(35);
double val_43 = -1.0;

val_43 = val_44 + val_47;
value_3 = val_43;

}


private void apply_0_9(InternalRow i) {

isN_67_0 = true;
UTF8String val_67 = null;

boolean isN_68 = i.isNullAt(18);
UTF8String val_68 = isN_68 ?
null : (i.getUTF8String(18));

if (!isN_68 && (isN_67_0 ||
(val_67.compare(val_68)) > 0)) {
isN_67_0 = false;
val_67 = val_68;
}


boolean isN_69 = i.isNullAt(40);
UTF8String val_69 = isN_69 ?
null : (i.getUTF8String(40));

if (!isN_69 && (isN_67_0 ||
(val_67.compare(val_69)) > 0)) {
isN_67_0 = false;
val_67 = val_69;
}
isNull_2 = isN_67_0;
mStArr_0[11] = val_67;

isN_70_0 = true;
UTF8String val_70 = null;

boolean isN_71 = i.isNullAt(19);
UTF8String val_71 = isN_71 ?
null : (i.getUTF8String(19));

if (!isN_71 && (isN_70_0 ||
(val_70.compare(val_71)) > 0)) {
isN_70_0 = false;
val_70 = val_71;
}


boolean isN_72 = i.isNullAt(41);
UTF8String val_72 = isN_72 ?
null : (i.getUTF8String(41));

if (!isN_72 && (isN_70_0 ||
(val_70.compare(val_72)) > 0)) {
isN_70_0 = false;
val_70 = val_72;
}
isNull_3 = isN_70_0;
mStArr_0[12] = val_70;

}


private void apply_0_0(InternalRow i) {

isN_0_0 = true;
UTF8String val_0 = null;

boolean isN_1 = i.isNullAt(0);
UTF8String val_1 = isN_1 ?
null : (i.getUTF8String(0));

if (!isN_1 && (isN_0_0 ||
(val_1.compare(val_0)) > 0)) {
isN_0_0 = false;
val_0 = val_1;
}


UTF8String val_2 = i.getUTF8String(22);

if (!false && (isN_0_0 ||
(val_2.compare(val_0)) > 0)) {
isN_0_0 = false;
val_0 = val_2;
}
mStArr_0[0] = val_0;

isN_3_0 = true;
long val_3 = -1L;

boolean isN_4 = i.isNullAt(1);
long val_4 = isN_4 ?
-1L : (i.getLong(1));

if (!isN_4 && (isN_3_0 ||
val_4 > val_3)) {
isN_3_0 = false;
val_3 = val_4;
}


long val_5 = i.getLong(23);

if (!false && (isN_3_0 ||
val_5 > val_3)) {
isN_3_0 = false;
val_3 = val_5;
}
value_0 = val_3;

}


private void apply_0_8(InternalRow i) {

isN_60_0 = true;
double val_60 = -1.0;
do {

boolean isN_61 = i.isNullAt(16);
double val_61 = isN_61 ?
-1.0 : (i.getDouble(16));
if (!isN_61) {
isN_60_0 = false;
val_60 = val_61;
continue;
}


isN_60_0 = false;
val_60 = 0.0D;
continue;

} while (false);
double val_63 = i.getDouble(38);
double val_59 = -1.0;

val_59 = val_60 + val_63;
value_6 = val_59;

isN_64_0 = true;
UTF8String val_64 = null;

boolean isN_65 = i.isNullAt(17);
UTF8String val_65 = isN_65 ?
null : (i.getUTF8String(17));

if (!isN_65 && (isN_64_0 ||
(val_64.compare(val_65)) > 0)) {
isN_64_0 = false;
val_64 = val_65;
}


UTF8String val_66 = i.getUTF8String(39);

if (!false && (isN_64_0 ||
(val_64.compare(val_66)) > 0)) {
isN_64_0 = false;
val_64 = val_66;
}
mStArr_0[10] = val_64;

}


private void apply_0_2(InternalRow i) {

isN_12_0 = true;
UTF8String val_12 = null;

boolean isN_13 = i.isNullAt(4);
UTF8String val_13 = isN_13 ?
null : (i.getUTF8String(4));

if (!isN_13 && (isN_12_0 ||
(val_13.compare(val_12)) > 0)) {
isN_12_0 = false;
val_12 = val_13;
}


UTF8String val_14 = i.getUTF8String(26);

if (!false && (isN_12_0 ||
(val_14.compare(val_12)) > 0)) {
isN_12_0 = false;
val_12 = val_14;
}
mStArr_0[3] = val_12;

isN_15_0 = true;
UTF8String val_15 = null;

boolean isN_16 = i.isNullAt(5);
UTF8String val_16 = isN_16 ?
null : (i.getUTF8String(5));

if (!isN_16 && (isN_15_0 ||
(val_16.compare(val_15)) > 0)) {
isN_15_0 = false;
val_15 = val_16;
}


UTF8String val_17 = i.getUTF8String(27);

if (!false && (isN_15_0 ||
(val_17.compare(val_15)) > 0)) {
isN_15_0 = false;
val_15 = val_17;
}
mStArr_0[4] = val_15;

}


private void apply_1_1(InternalRow i) {

if (!isNull_3) {
mutableRow.update(19, mStArr_0[12].copy());
} else {
mutableRow.setNullAt(19);
}

if (!isNull_4) {
mutableRow.update(20, mStArr_0[13].copy());
} else {
mutableRow.setNullAt(20);
}

}


private void apply_0_5(InternalRow i) {

isN_30_0 = true;
UTF8String val_30 = null;

boolean isN_31 = i.isNullAt(10);
UTF8String val_31 = isN_31 ?
null : (i.getUTF8String(10));

if (!isN_31 && (isN_30_0 ||
(val_31.compare(val_30)) > 0)) {
isN_30_0 = false;
val_30 = val_31;
}


boolean isN_32 = i.isNullAt(32);
UTF8String val_32 = isN_32 ?
null : (i.getUTF8String(32));

if (!isN_32 && (isN_30_0 ||
(val_32.compare(val_30)) > 0)) {
isN_30_0 = false;
val_30 = val_32;
}
isNull_1 = isN_30_0;
mStArr_0[9] = val_30;

isN_34_0 = true;
double val_34 = -1.0;
do {

boolean isN_35 = i.isNullAt(11);
double val_35 = isN_35 ?
-1.0 : (i.getDouble(11));
if (!isN_35) {
isN_34_0 = false;
val_34 = val_35;
continue;
}


isN_34_0 = false;
val_34 = 0.0D;
continue;

} while (false);
double val_37 = i.getDouble(33);
double val_33 = -1.0;

val_33 = val_34 + val_37;
value_1 = val_33;

}

}

**Comment by igreenfield** [comment]
@aunkrig Is this what you need?

**Comment by aunkrig** [comment]
Hi Izek,

I cannot compile and run your example without installing and understanding Spark, which I am not planning to do. Can you please provide a stand-alone example that depends solely on Janino?

CU Arno

**Comment by igreenfield** [comment]
[janino_issue.zip](https://github.com/janino-compiler/janino/files/12865799/janino_issue.zip)
I attached the full project.

**Comment by aunkrig** [comment]
Problem reproduced. Boils down to compiling this minimal class body:


    class SpecificMutableProjection {
    
        private void apply_0_7() {
    
            do {
                boolean isN_50 = false;
                long l = 33;
                continue;
            } while (this == null); // Doesn't matter if condition has constant value or not.
            
            int val_53 = 9;
            boolean isN_52 = false;
            long val_52 = -1L;         // <== java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
        }
    }

**Comment by igreenfield** [comment]
Can you explain more on this workaround?

**Comment by igreenfield** [comment]
@aunkrig When do you think there will be a fix for this?

**Comment by igreenfield** [comment]
@aunkrig 
I convert DO...WHILE into label and still get the error. 
this is the new code:
```public Object generate(Object[] refs) {
return new GeneratedIteratorForCodegenStage1(refs);
}

/*wsc_codegenStageId*/
final class GeneratedIteratorForCodegenStage1 extends org.apache.spark.sql.execution.BufferedRowIterator {
private Object[] refs;
private scala.collection.Iterator[] inputs;
private scala.collection.Iterator inadp_input_0;
private boolean prj_prj_isN_0_0;
private boolean prj_prj_isN_5_0;
private boolean prj_prj_isN_8_0;
private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter[] prj_mStArr_0 = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter[2];

public GeneratedIteratorForCodegenStage1(Object[] refs) {
this.refs = refs;
}

public void init(int index, scala.collection.Iterator[] inputs) {
partitionIndex = index;
this.inputs = inputs;
inadp_input_0 = inputs[0];

prj_mStArr_0[0] = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(5, 96);
prj_mStArr_0[1] = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(7, 160);

}

protected void processNext() throws java.io.IOException {
while ( inadp_input_0.hasNext()) {
InternalRow inadp_row_0 = (InternalRow) inadp_input_0.next();

// common sub-expressions

prj_prj_isN_0_0 = true;
UTF8String prj_val_0 = null;
prj_lbl__0: {
boolean inadp_isN_0 = inadp_row_0.isNullAt(0);
UTF8String inadp_val_0 = inadp_isN_0 ?
null : (inadp_row_0.getUTF8String(0));
if (!inadp_isN_0) {
prj_prj_isN_0_0 = false;
prj_val_0 = inadp_val_0;
break prj_lbl__0;
}

prj_prj_isN_0_0 = false;
prj_val_0 = ((UTF8String) refs[0] /* literal */);
break prj_lbl__0;

}

// common sub-expressions

boolean inadp_isN_1 = inadp_row_0.isNullAt(1);
double inadp_val_1 = inadp_isN_1 ?
-1.0 : (inadp_row_0.getDouble(1));
boolean inadp_isN_2 = inadp_row_0.isNullAt(2);
double inadp_val_2 = inadp_isN_2 ?
-1.0 : (inadp_row_0.getDouble(2));
prj_prj_isN_5_0 = true;
UTF8String prj_val_5 = null;
prj_lbl__1: {
boolean inadp_isN_3 = inadp_row_0.isNullAt(3);
UTF8String inadp_val_3 = inadp_isN_3 ?
null : (inadp_row_0.getUTF8String(3));
if (!inadp_isN_3) {
prj_prj_isN_5_0 = false;
prj_val_5 = inadp_val_3;
break prj_lbl__1;
}

prj_prj_isN_5_0 = false;
prj_val_5 = ((UTF8String) refs[1] /* literal */);
break prj_lbl__1;

}
prj_prj_isN_8_0 = true;
UTF8String prj_val_8 = null;
prj_lbl__2: {
boolean inadp_isN_4 = inadp_row_0.isNullAt(4);
UTF8String inadp_val_4 = inadp_isN_4 ?
null : (inadp_row_0.getUTF8String(4));
if (!inadp_isN_4) {
prj_prj_isN_8_0 = false;
prj_val_8 = inadp_val_4;
break prj_lbl__2;
}

prj_prj_isN_8_0 = false;
prj_val_8 = ((UTF8String) refs[2] /* literal */);
break prj_lbl__2;

}
prj_mStArr_0[1].reset();

prj_mStArr_0[1].zeroOutNullBytes();

prj_mStArr_0[1].write(0, prj_val_0);

if (inadp_isN_1) {
prj_mStArr_0[1].setNullAt(1);
} else {
prj_mStArr_0[1].write(1, inadp_val_1);
}

if (inadp_isN_2) {
prj_mStArr_0[1].setNullAt(2);
} else {
prj_mStArr_0[1].write(2, inadp_val_2);
}

prj_mStArr_0[1].write(3, prj_val_5);

prj_mStArr_0[1].write(4, prj_val_8);

prj_mStArr_0[1].write(5, prj_val_0);

prj_mStArr_0[1].write(6, prj_val_0);
append((prj_mStArr_0[1].getRow()));
if (shouldStop()) return;
}
}

}```

**Comment by igreenfield** [comment]
@aunkrig Why it is still tagged as `waiting for user` ?

**Comment by aunkrig** [comment]
How is the "new code" related to the old code?

And again: Can you please provide a stand-alone example that depends solely on Janino? I understand that you want your problem be solved in your environment, but someone has to isolate and minimize it, and I think that should be you.

**Comment by igreenfield** [comment]
1. the new code is with your workaround, using labels and not DO...WHILE.
2. if you paste the code in the project I sent you it will be compiled.
3. What about the first issue with the DO...WHILE?

**Comment by aunkrig** [comment]
I believe I fixed it. Please test.

**Comment by igreenfield** [comment]
@aunkrig for my test it solves the issue, so please release a new version. thanks.

**Comment by aunkrig** [comment]
🕺🕺🕺

**Comment by igreenfield** [comment]
@aunkrig Can you please release a new version with this fix? it is very urgent for me. thanks.

**Comment by aunkrig** [comment]
Version 3.1.11 is out the door! Please test.

**Comment by igreenfield** [comment]
it is good, thanks.
