### ISSUE TITLE
Unable to execute script from the app launched as jar

### ISSUE THREAD

**Issue by nikolayandr** [janino-compiler/janino#211]
Hi to everyone. I was able to catch the next bad case:
1) Spring boot app run as jar
2) Janino compiler is run by third library(datomic) written in groovy
3) org.codehaus.commons.compiler.jdk.ClassLoaders#getSubresourcesOf(java.net.URL, java.lang.String, boolean, boolean) throws NPE due to null jar entry, see screnshots below

![image](https://github.com/janino-compiler/janino/assets/4941456/005d6f74-94ec-4a70-a620-cfb6970c9112)
![image](https://github.com/janino-compiler/janino/assets/4941456/7e1a5bcc-7824-42c9-a3fe-c50e843a4a0b)

P.S. When I run the app from IDE then all is okay
Library version: 3.0.16
OS: Ubuntu
Java: 11 and 17

**Comment by aunkrig** [comment]
The problem appears to originate from the class path. The class path must contain either *directories*, or *jar files*, like:

    jar:file:/myjarfile.jar!/BOOT-INF/classes
    jar:file:/myjarfile.jar!/BOOT-INF/lib!thejarfile.jar

But your app appears to have a class path like

    jar:file:/myjarfile.jar!/BOOT-INF/classes!/
    jar:file:/myjarfile.jar!/BOOT-INF/lib!thejarfile.jar!/

While the latter ("...jarfile.jar!/") may be equivalent with "...jarfile.jar", the former (".../classes!/") is certainly not equivalent with ".../classes", because "classes" is *not* a jar file.

Is it possible to run your app with the correct class path?

**Comment by nikolayandr** [comment]
@aunkrig thank you for your response.

`!` is not part of the name `classes` as you might see on the screenshot below
![image](https://github.com/janino-compiler/janino/assets/4941456/57613992-12fd-4bbd-ae27-a9945fe689be)

> Is it possible to run your app with the correct class path?
Sorry, maybe I did not get what you meant, could you please clarify what means correct class path? The app is run as a simple jar, nothing special is done to modify class path/class loader

I see the next list of URLS returned by calling `java.lang.ClassLoader#getResources`
![image](https://github.com/janino-compiler/janino/assets/4941456/18d8e91f-e969-4104-906e-d646a8b26bc8)


I have found a good explanation of what the second `!` means https://www.appsloveworld.com/java/100/815/why-classloader-returns-a-path-with-extraneous-second-exclamation-point

**Comment by nikolayandr** [comment]
> Is it possible to run your app with the correct class path?

Sorry, I got what you mean, my jar is the bootable bundle jar(all dependencies are inside the jar) and it does not require any additional classpath passed to JVM

**Comment by aunkrig** [comment]
I cannot reproduce the problem. The JAVADOC of `JarURLConnection.getJarEntry()` says

> This method returns null if the JAR file URL corresponding to this connection points to a JAR file and not a JAR file entry.

But the connection doesn't point to a JAR file, and thus the method shouldn't return `null`. When I try to reproduce it locally, I get

> java.io.FileNotFoundException: JAR entry BOOT-INF/classes!/ not found in \dev\workspaces\janino\issue211\foo.jar

, which is correct.

Your Janino version is very old, (3.0.16 = 2020-03-18), and `org.codehaus.commons.compiler.jdk` had a major rewrite in 3.1.7. Can you please update to the latest version? It makes no sense to dig in that ancient version...

**Comment by nikolayandr** [comment]
@aunkrig @aunkrig I Agree about the old version but unfortunately, this version is used by a third library we depend on. Ok, thank you for your explanation

**Comment by aunkrig** [comment]
The API of Janino is quite stable... you might update the Janino libs without updating your third-party library, and chances are that it still works.

**Comment by nikolayandr** [comment]
> The API of Janino is quite stable... you might update the Janino libs without updating your third-party library, and chances are that it still works.

@aunkrig I Already tried but unfortunately, a class cast exception happens when we try to use newer versions, I'm not sure how exactly third-party library uses `janino`, it is `datomic clojure library` not so easy to debug this library. Anyway, thank you for your help
