### ISSUE TITLE
Where can I see release notes for this project?

### ISSUE THREAD

**Issue by yeikel** [janino-compiler/janino#213]
To help understand what changed between versions. ie : between the patch `3.1.11` and `3.1.12`

I will look at the diff in the meantime : https://github.com/janino-compiler/janino/compare/v3.1.11...v3.1.12

**Comment by aunkrig** [comment]
The change log is at https://janino-compiler.github.io/janino/changelog.html, and it is up-to-date... If you don't see the 3.1.12 changes there, maybe your browser caches the document; Shift+F5 should help.

To be sure to be sure, here's the relevant snippet for the change log:

> ### Version 3.1.12 2024-02-06
> * Fixed issue #212 "Assignment conversion not possible from type"
> * Fixed issue #209: Use Java's ServiceLoader instead of org.codehaus.commons.compiler.properties
> * Added test case for issue #169 "Problems with varargs and inheritance".
> * Fixed issue #210 "CompilerException with static inner classes".
>

**Comment by yeikel** [comment]
> The change log is at https://janino-compiler.github.io/janino/changelog.html, and it is up-to-date... If you don't see the 3.1.12 changes there, maybe your browser caches the document; Shift+F5 should help.
> 
> To be sure to be sure, here's the relevant snippet for the change log:
> 
> > ### Version 3.1.12 2024-02-06
> > 
> > * Fixed issue [Assignment conversion not possible from type InterfaceClass to type AbstractClass #212](https://github.com/janino-compiler/janino/issues/212) "Assignment conversion not possible from type"
> > * Fixed issue [Use Java's ServiceLoader instead of org.codehaus.commons.compiler.properties #209](https://github.com/janino-compiler/janino/issues/209): Use Java's ServiceLoader instead of org.codehaus.commons.compiler.properties
> > * Added test case for issue [Problems with varargs and inheritance #169](https://github.com/janino-compiler/janino/issues/169) "Problems with varargs and inheritance".
> > * Fixed issue [CompilerException with static inner classes #210](https://github.com/janino-compiler/janino/issues/210) "CompilerException with static inner classes".

Awesome, thank you. It seems that I did not look hard enough
