### ISSUE TITLE
Javadoc search appears to be broken

### ISSUE THREAD

**Issue by nchammas** [janino-compiler/janino#215]
Starting here:

https://janino-compiler.github.io/janino/apidocs/

I search for `Integer` using the search bar in the top right corner and click on the first link, which sends me here:

https://janino-compiler.github.io/janino/apidocs/undefined/org/codehaus/janino/Java.IntegerLiteral.html

But this is a 404.

**Comment by aunkrig** [comment]
For some reason, the JAVADOC search produces a target URL

> https://janino-compiler.github.io/janino/apidocs/undefined/org/codehaus/janino/Java.IntegerLiteral.html

instead of

> https://janino-compiler.github.io/janino/apidocs/org/codehaus/janino/Java.IntegerLiteral.html

Why??

**Comment by aunkrig** [comment]
The solution is https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url#answer-52603413

**Comment by aunkrig** [comment]
Update online JAVADOC from 3.1.2-SNAPSHOT to 3.1.13-SNAPSHOT.

Please test!

**Comment by nchammas** [comment]
Works for me now. 👍
