### ISSUE TITLE
jdk1.8 grammer

### ISSUE THREAD

**Issue by Stevengmk** [janino-compiler/janino#216]
Does Janino compiler supports compiling JDK1.8 grammer?

**Comment by aunkrig** [comment]
Hey Steven,

not totally sure what you mean... Janino can parse and unparse the complete Java grammar, but it can *compile* only a subset of the language, which is described in detail on the homepage:

http://janino-compiler.github.io/janino/#properties


CU Arno

**Comment by aunkrig** [comment]
Did that help?

**Comment by Stevengmk** [comment]
> Did that help?

yeah，3q

**Comment by aunkrig** [comment]
You're welcome!
