### ISSUE TITLE
what is the limit size of java code  that Janino compile? 

### ISSUE THREAD

**Issue by QQshu1** [janino-compiler/janino#23]
I use a Oracle JDK compile the Java source(the code size 2000 rows), and find it excute faster than Janino . (may be fast 60 s) , does Janino has limit on the size of Java source? thanks.

**Comment by aunkrig** [comment]
Are that two questions?
(1) I'm surprised to hear that JAVAC compiles a 2000 lines faster than JANINO. Can you please provide an example compilation unit so I can reproduce your benchmark?
(2) JANINO has no size limitations other than those imposed by the JVM, e.g. 64 kb bytecode per method.
