### ISSUE TITLE
StackOverflow when using new Permision system in ClassLoader

### ISSUE THREAD

**Issue by mathieu-veron** [janino-compiler/janino#25]
Hello,
I'm in the context of a tomcat 6 webapp, using janino 3.0.7
My code is much like the documented code in the security section

What happens is a stackoverflow originated by 
SecurityMamanger.checkRead calling the SandBox.checkPermission

In my case here is the loop created

SecurityMamanger.checkRead:888
code : checkPermission(new FilePermission(file,SecurityConstants.FILE_READ_ACTION));

 SandBox$1.checkPermission:82
 code : acc = Sandbox.CONFINED_CLASS_LOADERS.get(clasS.getClassLoader());

  Class.getClassLoader:683
    ClassLoader.checkClassLoaderPermission:1528
  
       who again call :  SandBox$1.checkPermission:82

And so we are from here stuck in a loop which lead to a S.O.

**Comment by aunkrig** [comment]
The reason being is that the sandbox's security manager invokes "Class.getClassLoader()", which in turn calls the security manager's "checkPermission()" method. Bummer.

**Comment by aunkrig** [comment]
This problem occurs iff the class loader of the "Sandbox.class" is _not_ an ancestor of the context class's class loader.

**Comment by aunkrig** [comment]
Would you please be so kind and post the _complete_ stack trace, so I can see which class requests READ permission?

**Comment by aunkrig** [comment]
Also, please try and change the following lines in "sandbox.java":

    for (Class<?> clasS : this.getClassContext()) {
        if (clasS == this.getClass()) return;    // <= That should prevent infinite recursion.

**Comment by mathieu-veron** [comment]
Hello,
Just grab the compiler 3.0.8 snapshot from the trunk, and it solve the issue (and the unit test are still working). thx. Do you still need the full stack trace ?
