### ISSUE TITLE
Import silently failing

### ISSUE THREAD

**Issue by MattJohns** [janino-compiler/janino#28]
Not sure of the exact problem and it's difficult to post an example unfortunately, but I can try if this is an unknown issue.  I seem to be getting a compile error when trying to reference a class that is full of static items.  The import is correct but the compiler says it's an error.

The class being references is like this:
```
public class MyStaticClass {
    public static final SomeOtherClass ITEM1;

    static {
        ITEM1 = new SomeOtherClass("abc");
    }
}
```
Then I reference that static item from my code that I am loading with SimpleCompiler:

```
public void someMethod() {
    SomeOtherClass c1 = MyStaticClass.ITEM1;
}
```

Error text just points to the line number and position in someMethod().

I apologize for the lack of actual code example but let me know if this is not a known issue and i'll try to provide more information.  The actual error is being caused within a Minecraft mod and their code undergoes deobfuscation etc. so a bit hard to provide an example.

**Comment by aunkrig** [comment]
Hi Matt,

haven't heared of that problem so far... please provide as many details as possible, esp. the version and the error message.


CU Arno

**Comment by MattJohns** [comment]
Thanks for the quick response.  I set up a test in a new project with some simple classes and couldn't reproduce.  So I assume it's something more complicated and will let you know if I find anything.  Feel free to close this but i'll make sure to notify you either way.

**Comment by MattJohns** [comment]
After more inspection it appears the system I'm using (Minecraft Forge) does special class loading for my code.  I've tried setting the parent class loader of the SimpleCompiler to all different kinds of things but it always fails when trying to read a static member from Janino code.

I can give you a skeleton example if you're interested but I don't expect anything because Janino works fine when the skeleton is used without Minecraft Forge.  So feel free to close this Issue.

**Comment by aunkrig** [comment]
> but it always fails

Please explain how "it" (?) "fails" (compile error, stack trace, ...).

> when trying to read a static member from Janino code

What do you mean? A member type, member field or member method? Does JANINO read it, or Minecraft Forge?

Maybe that information is already enough to get closer to the problem.

**Comment by MattJohns** [comment]
Here are the full steps to reproduce, and i'll write a separate comment below describing the issue:

1. Create a new folder for the project called "JaninoTestProject" anywhere on the system.  Inside that create a subfolder called "JaninoTest" and extract the content of the attached zip file "JaninoIssueJun2017.zip" in there.

2. On the command line in folder "JaninoTest", run "gradlew setupDecompWorkspace".  This downloads the Minecraft libraries.  Then run "gradlew eclipse".

3. Open Eclipse and choose "JaninoTestProject" as the workspace folder.  Then once inside Eclipse, import the existing project using that folder.

4. Right click the src folder in project explorer, select "Build Path", "Use as source folder".

5. Add Janino jars to project.

6.  Create "c:\JaninoSource\" folder and extract the content of attached "ExternalSource.zip" into there.

It should be ready to run, you'll see comments in ModMain class that describe the issue.

[JaninoIssueJun2017.zip](https://github.com/janino-compiler/janino/files/1081594/JaninoIssueJun2017.zip)

[ExternalSource.zip](https://github.com/janino-compiler/janino/files/1081602/ExternalSource.zip)

**Comment by MattJohns** [comment]
You'll might prefer to just look at the source in ModMain.java .  It shows that regardless of which class loader is used the external source is unable to load properly.

- If you use the system class loader then everything works fine except the external source code is unable to 'communicate' with the main code, because it's loaded using a different class loader.  The attempt to cast the external class to an interface fails because of that.

- If you use the class loader that is used for the main code instead, then cookFile() fails in a strange way.  It is unable to find java.lang.String without an import.  If you add the import line it then fails when trying to access any class in the main code.

I tried doing the exact same test but without any Minecraft involved and it all worked fine.  So that's why I place the blame on their end.  Unfortunately their forum is unhelpful and toxic so they are of no help.

Ultimately it's not a big problem because it's only for an open source game modification.  And it's very possibly a problem with my poor understanding of class loaders.

**Comment by MattJohns** [comment]
I managed to fix it by creating a custom class loader.  The problem was the game creates a special class loader that has no parent, so it is unable to find system classes like java.lang.* .

But now I am running into a new issue when trying to use JavaSourceClassLoader rather than SimpleCompiler.  It seems to give a ClassNotFoundException even with a simple test case:

```
package mainpackage;

import java.io.File;
import org.codehaus.janino.JavaSourceClassLoader;

public class Main {
	public static void main(String [] args) {
		try {
			File directory = new File("c:\\ExternalSource");
			ClassLoader classLoader = new JavaSourceClassLoader (
	                Main.class.getClassLoader(),
	                new File[]{directory},
	                (String)null);
			
			// class not found exception
			Class<?> newClass = classLoader.loadClass("mainpackage.Test1"); 
		}
		catch (Exception exception) {
		}
	}
}

/*
Content of "c:\ExternalSource\Test1.java":

package mainpackage;

public class Test1 {
} 

*/
```

I must be doing something fundamentally wrong because there are plenty of examples online of people using JavaSourceClassLoader without any issue.

**Comment by MattJohns** [comment]
I've worked it out.  The folder structure needs to reflect the package structure.

All issues are solved so i'll close it.
