### ISSUE TITLE
Proper author for citation in academic paper

### ISSUE THREAD

**Issue by he-sk** [janino-compiler/janino#29]
How should Janino be cited in an academic paper? Specifically, I need something to fill into the author field. Should I use "Janino Compiler Project"?

**Comment by aunkrig** [comment]
Hello Viktor,

since 99% of the code was written by me, I think it is appropriate to call me the author.


CU Arno

**Comment by he-sk** [comment]
Hi Arno,

So "Arno Unkrig et al." it is.

Best,
Viktor

**Comment by aunkrig** [comment]
Agreed!
