### ISSUE TITLE
Please create tags/releases

### ISSUE THREAD

**Issue by wltjr** [janino-compiler/janino#37]
Please create/add tags for downloadable source tarballs/zipfiles under releases. Thank you!

**Comment by oontvoo** [comment]
Hi, 
For download, please see the Download section on this [page](http://janino-compiler.github.io/janino/#installation). 
The short version is that, if you're **not** using maven, please do the following:

- Download the latest version of ["janino-version.jar".](http://repo1.maven.org/maven2/org/codehaus/janino/janino/)
- Download the same version of ["commons-compiler-version.jar"](http://repo1.maven.org/maven2/org/codehaus/janino/commons-compiler/).
- Put the two JAR files on your classpath.

Regarding tags/branches, admittedly, we haven't been good at keeping. We'll do that next time. :)

**Comment by wltjr** [comment]
FYI have packaged this, [Gentoo ebuild for janino](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java/janino). I went ahead and forked the repo to create the [release source tarball/zipfile](https://github.com/Obsidian-StudiosInc/janino/releases).
