### ISSUE TITLE
Uninitialized Variables

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#38]
First and foremost, Janino is really cool. I'm using it for in-class in-browser examples for an intro programming class and it's a lot of fun.

That said, the following doesn't seem to work properly:
```java
int i;
System.out.println(i);
```
I suppose it is up to the compiler to initialize uninitialized values appropriately, and apparently Janino decides to fail rather than follow the common behavior of setting i to zero. But it would be nice if it matched the behavior of more standard (and slower) compilers.

**Comment by gchallen** [comment]
OK fair enough. Why did I think that this worked? Did it work in previous versions of Java? Their webpage states that [It's not always necessary to assign a value when a field is declared. Fields that are declared but not initialized will be set to a reasonable default by the compiler. Generally speaking, this default will be zero or null, depending on the data type.](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html).

Anyway, thanks for the response.

**Comment by aunkrig** [comment]
FIELDS are initialized with default values, LOCAL VARIABLES are not. It‘s always been like that, from 1.0 through 9.
