### ISSUE TITLE
Private Variables in Script Execution Mode

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#40]
First and foremost, thanks _a ton_ for Janino. I've been using it to run [in-class examples](https://cs125.cs.illinois.edu/learn/objectintroduction/) for my introductory programming course and it's working brilliantly.

I'm confused, however, as to why the following works:

````java
class Test {
  private int value;
}
Test t = new Test();
t.value = 5;
System.out.println(t.value);
````

Is there a way to get the visibility modifiers to work in examples like this? Note that I'm currently disabling almost all permissions—with the exception of `RuntimePermission("getProtectionDomain")` which I needed to enable to get class loading to work at all. Perhaps I'm disabling a permission that is causing this work work incorrectly?

FWIW, the code for Janini (my script runner web service) is available [here](https://github.com/cs125-illinois/janini/blob/master/src/main/java/WebServer.java).

**Comment by oontvoo** [comment]
Hi, 
I didn't get to your script, but it's worth pointing out that in Java, "private" essentially means accessible within that class **file**.
So for example, the following code is valid even though a private variable x is being accessed from outside of its class.

`public class Test {
    public static class Foo {
	private int x = 0;
    }

    public static void main(String[] args) {
	Foo f = new Foo();
	f.x = 1;
	System.out.println(f.x);
    }
}`

**Comment by gchallen** [comment]
I understand that. At least I hope I do—I do teach this stuff to hundreds of students 🙂. But it script mode it's not clear that the code outside the class (in my example above) runs _inside_ the class it is next to. And it could be more complex than that:

````java
class Test {
  private int value;
}
class Example {
   private int value;
}
// Should I be able to access private members of Test and Example?
````

**Comment by aunkrig** [comment]
Hi Geoffrey,

to understand why JANINO allows that access, you have to know that the input of the ```ScriptEvaluator``` is a _method body_. That means that any classes you declare in a script are _local classes_, which has some implications:
* You can only declare _classes_, not _interfaces_.
* The class declaration is implicitly ```private```, and must have no modifiers.
* Methods of that local class have access to any ```final``` local variables previously declared in the enclosing method.
* The code of the enclosing method (i.e. the "script code") has unlimited access to all members of any previously declared local classes. Effetively, it does not make any sense to declare any ```private``` members in local classes.

BTW, the same is true for _member types_: Methods declared in type A can access all members of type B iff A encloses B, or B encloses A, or A _and_ B are enclosed by the same type C.

Summarized, it's a feature, not a bug ;-) . However I get your point. I'll check if there's a simple way to write an alternate ```ScriptEvaluator``` that forbids access to declared classes' ```private``` members.

**Comment by aunkrig** [comment]
I implemented an (experimental) feature ```ScriptEvaluator.options().add(JaninoOptions.PRIVATE_MEMBERS_OF_ENCLOSING_AND_ENCLOSED_TYPES_INACCESSIBLE)```, which hopefully does the trick.

Please test and verify that this is what you wanted.

**Comment by gchallen** [comment]
Sorry... haven't had a chance to test this out yet. Once I do I'll let you know. With 500 students I try not to change things in the middle of the semester unless I absolutely have to.

**Comment by gchallen** [comment]
Sorry for the delay—overall this looks great. Will this make its way into a release?
