### ISSUE TITLE
Invalid integer literal "9223372036854775808L"

### ISSUE THREAD

**Issue by rednaxelafx** [janino-compiler/janino#41]
Janino trips over when compiling a negation on minimal values of `int` and `long`. e.g. for the following code snippet:
```java
long value = -(-9223372036854775808L);
```
Janino would throw an exception saying `Invalid integer literal "9223372036854775808L"`, while javac compiles it fine.

**Comment by aunkrig** [comment]
I found a very elegant way to fix this problem, and thus reject your PR #42.

**Comment by rednaxelafx** [comment]
Thanks @aunkrig ! Unfortunately that fix will only fix that exact test case I added but not the following:
```java
- -9223372036854775808L
```
The point is there doesn't have to be parenthesis to get you into this situation.

**Comment by aunkrig** [comment]
You're absolutely right! Amazingly, I found _another_ simplification (saves 78 LOC) that hopefully fixes the bug completely. Please test!

**Comment by rednaxelafx** [comment]
@aunkrig Awesome! Works for me now! Thank you very much 👍
