### ISSUE TITLE
Invalid JavaDoc comment on VariableAccessResource constructor

### ISSUE THREAD

**Issue by rednaxelafx** [janino-compiler/janino#45]
After the recent addition of try-with-resources support, the newly added `VariableAccessResource` seems to be suffering from some copy-and-paste error:
(from `org.codehaus.janino.Java.TryStatement.VariableAccessResource#VariableAccessResource`)
```java
            /**
             * @param modifiers Only {@code final} allowed
             */
            public
            VariableAccessResource(Location location, Rvalue variableAccess) {
                super(location);
                this.variableAccess = variableAccess;
            }
```

**Comment by aunkrig** [comment]
Thanks!

**Comment by rednaxelafx** [comment]
@aunkrig Thank you for the great work, as always!
