### ISSUE TITLE
Conversion not possible when generics in play.

### ISSUE THREAD

**Issue by zolyfarkas** [janino-compiler/janino#5]
org.codehaus.commons.compiler.CompileException: File './target/1473454439101-0/test.java', Line 1078, Column 31: Assignment conversion not possible from type "java.lang.Object" to type "boolean"

the code line looks like:

      this.boolean = method(someObject, someBoolean);

method signature is:

<T>  T method(Object obj, T someBool)

This is with janino 3.0.1

**Comment by aunkrig** [comment]
You've stumbled across one of the limitations of JANINO: JANINO doesn't know "parameterized types", so it thinks that the method returns an Object.

Casting the result of the method invocation to "(Boolean)" should do the trick. If not, let me know.

**Comment by zolyfarkas** [comment]
Thanks... modified the code generator to bypass this issue, unfortunately the code generator is a 3rd party lib and I will have to fork it...
Any plans in the future to eliminate this limitation?

**Comment by aunkrig** [comment]
Types are the one big limitation of JANINO, but they're terribly complicated to implement. I once made an attempt, but gave up when it was half done. Tell my employer to grant me a proper sabbatical! ;-)

**Comment by zolyfarkas** [comment]
Haha :-) sounds familiar, types have been on my todo list for zel (http://zolyfarkas.github.io/spf4j/spf4j-zel/index.html)... for years... together with a long list of other things that I would like to do...  in any case thanks!

**Comment by palepal** [comment]
@aunkrig I think I have the same problem, but I have near-zero Java experience, so I cannot make this work. Can you help me out? :)

```java
import com.google.i18n.phonenumbers.*;
import java.util.*;

public boolean processRow(StepMetaInterface smi, StepDataInterface sdi) throws KettleException
{
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();

Iterator iterator = phoneUtil.findNumbers("bla", null).iterator();

while (iterator.hasNext()) {
	PhoneNumberMatch match =  iterator.next();
	if (match != null) {
		//row5.outPhone = phoneUtil.format(match.number(), PhoneNumberFormat.E164);
	concat += "bla"; 
	}
}
}
```

Line 11, Column 19: Assignment conversion not possible from type "java.lang.Object" to type "com.google.i18n.phonenumbers.PhoneNumberMatch"

**Comment by palepal** [comment]
If anyone stumbles upon this because they are using Pentaho for ETL and custom Java step with liphonenumber, then you have to do this to make it work:
PhoneNumberMatch match =  (PhoneNumberMatch)iterator.next();
