### ISSUE TITLE
Cooking Multiple Files with SimpleCompiler

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#52]
Is it possible to cook multiple strings using the Janino `SimpleCompiler`? I tried something like this:

````java
for (String source : sources) {
    simpleCompiler.cook(new ByteArrayInputStream(source.getBytes(StandardCharsets.UTF_8)));
    simpleCompiler.setParentClassLoader(simpleCompiler.getClassLoader());
}
````
This works fine as long as the dependencies are in the correct order, but fails if they are not. In contrast, feeding in one string with both class definitions works regardless of in which order the classes are defined.

An obvious approach is to try and concatenate the files together and feed them all in at once, but that fails if there are imports at the top of each class file.

Overall I'd like to be able to take a request containing multiple strings each containing a Java class file with imports, compile them all and then run something. It seems like Janino is really close to being able to do that...

**Comment by aunkrig** [comment]
What you are looking for is the `org.codehaus.janino.Compiler`(as opposed to the `SimpleCompiler`).

`CompilerTest.testCompileErrors()` demonstrates the API.

**Comment by aunkrig** [comment]
Another way is to use the `JavaSourceClassLoader`. I will add examples.

**Comment by aunkrig** [comment]
I just streamlined the `Compiler` API... be sure to use the HEAD version.

**Comment by gchallen** [comment]
Ah, OK. Very cool.

BTW: what's the recommended way to get at the latest releases? Would you be willing to publish this on Jitpack so that we can pull HEAD using Gradle?

**Comment by aunkrig** [comment]
Please don't post unrelated questions in an existing issue ("combo issue"). That makes tracking really tedious.
To answer your question: JANINO is published on MAVEN CENTRAL, together with JAVADOC and sources.
