### ISSUE TITLE
Java 11 Compatibility check: commons-compiler

### ISSUE THREAD

**Issue by KryniuPL** [janino-compiler/janino#55]
Hi,
We are reaching out to you to check Java 11 compatibility of the library commons-compiler.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by aunkrig** [comment]
Ran the regression test suite against various later JREs, successfuly, and documented the results here:

http://janino-compiler.github.io/janino/#requirements
