### ISSUE TITLE
How can I find out the object memory size

### ISSUE THREAD

**Issue by wenerme** [janino-compiler/janino#56]
Question like this https://stackoverflow.com/questions/9368764 

Get Instrumentation is not easy, if janino can compile the code, is it possible to tell me the object memory size ?

**Comment by aunkrig** [comment]
No, object sizes can only be determined at runtime, because they depend on the JRE. E.g., object references take up 4 bytes in 32 bit environments, and 8 bytes in 64 bit environments.
