### ISSUE TITLE
Integer overflow in ClassFile reader

### ISSUE THREAD

**Issue by rednaxelafx** [janino-compiler/janino#58]
There's a pattern of integer overflow issues in the `ClassFile` read path.

e.g. https://github.com/janino-compiler/janino/blob/master/janino/src/main/java/org/codehaus/janino/util/ClassFile.java#L708
```java
    /**
     * u2 attributes_count, attributes[attributes_count]
     */
    private List<AttributeInfo>
    loadAttributes(DataInputStream dis) throws IOException {
        short               attributesCount = dis.readShort();
        List<AttributeInfo> attributes      = new ArrayList<AttributeInfo>(attributesCount);
        for (int i = 0; i < attributesCount; ++i) attributes.add(this.loadAttribute(dis));
        return attributes;
    }
```
The Class file format says the attribute_count is a `u2`, but it's read here with `dis.readShort()` so that's reading as a signed `short`.

In some Class files that Spark generates, various sizes/counts can be really big, above the signed ranges of the corresponding integer types, so when Janino reads in such files, they're subject to weird exceptions like:
```
java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at org.codehaus.janino.util.ClassFile.loadAttribute(ClassFile.java:1808)
        at org.codehaus.janino.util.ClassFile.loadAttributes(ClassFile.java:698)
        at org.codehaus.janino.util.ClassFile.loadFields(ClassFile.java:673)
        at org.codehaus.janino.util.ClassFile.<init>(ClassFile.java:299)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anonfun$29.apply(CodeGenerator.scala:1674)
        ... 
```

In one such cases, the constant pool had a lot of entries:
```
...
  #49449 = Utf8               <init> 
  #49450 = Utf8               (Lorg/apache/spark/sql/catalyst/expressions/GeneratedClass$SpecificMutableProjection;)V
  #49451 = Utf8               ()V    
  #49452 = NameAndType        #49449:#49451 // "<init>":()V
  #49453 = Methodref          #4.#49452   // java/lang/Object."<init>":()V
{
```
`(short)49453` interpreted as a signed short is `-16083`, which probably overflows the following code:
https://github.com/janino-compiler/janino/blob/master/janino/src/main/java/org/codehaus/janino/util/ClassFile.java#L664
```java
short constantPoolCount = dis.readShort(); // constant_pool_count
```

**Comment by rednaxelafx** [comment]
Awesome! Tried it out and works like a charm for the specific Class file I had in hand, thank you so much, @aunkrig !

But there might still be some more similar issues lying around somewhere. For example,
From JVMS8:
```
method_info {
    u2             access_flags;
    u2             name_index;
    u2             descriptor_index;
    u2             attributes_count;
    attribute_info attributes[attributes_count];
}
```
Here's how Janino parses it: https://github.com/janino-compiler/janino/blob/129048c35269e878adb36da0c39e7ade00c71998/janino/src/main/java/org/codehaus/janino/util/ClassFile.java#L1672
```java
    private MethodInfo
    loadMethodInfo(DataInputStream dis) throws IOException {
        return new MethodInfo(
            dis.readShort(),         // access_flags
            dis.readShort(),         // name_index       // NOTE
            dis.readShort(),         // descriptor_index // NOTE
            this.loadAttributes(dis) // attributes_count, attributes[attributes_count]
        );
    }
```
So there's a potential that'll run into some issues too when a method name/descriptor is at the rear end of a large constant pool.

My take on the Spark's usage of Janino is that, because this issue only appears on an optional "metrics collection" path and when Janino hits an error Spark just swallows it and logs a warning "error collecting metrics", people haven't really paid attention to this before.
Spark does generate huge Class files from time to time, with a large constant pool and large method bodies.

**Comment by aunkrig** [comment]
Hey Kris,

I understand what you mean, but I checked that and there shouldn't be a problem: References to the constant pool are handled properly:

```java
    public ConstantPoolInfo
    getConstantPoolInfo(short index) {
        return (ConstantPoolInfo) this.constantPool.get(0xffff & index);
    }
```

Constant pool size limits have been thoroughly tested, so I'm optimistic that these are not a problem.

Do you want an official JANINO release?

**Comment by aunkrig** [comment]
Well, if there's a good reason to do so... version 3.0.10 is out the door, and will soon find its way to search.maven.org.
