### ISSUE TITLE
Optimize static method invocation with rvalue target expression

### ISSUE THREAD

**Issue by aunkrig** [janino-compiler/janino#62]
https://github.com/apache/drill/branches/1.14.0/exec/java-exec/src/main/java/org/apache/drill/exec/compile/bytecode/AloadPopRemover.java
correctly reports that Janino doesn't optimize this case:
```
localVariable.staticMethod();
```
The code generated by Janino retrieves the local variable value and immediately discards it.

**Comment by aunkrig** [comment]
Janino now checks if the target expression has side effects, and if not, completely eliminates the code.
`UnitCompiler.compileGet2(MethodInvocation mi)`.

**Comment by vvysotskyi** [comment]
@aunkrig, thanks for fixing this issue!
I tried to reproduce it in Drill, but all tests are passed when this workaround is removed, so I can't verify it.

**Comment by vvysotskyi** [comment]
Yes, that means "problem resolved", but perhaps in one of the previous releases. Thanks!

**Comment by aunkrig** [comment]
Version 3.0.11 is out the door, and includes the fix for this issue.
