### ISSUE TITLE
Script with many "helper" variables

### ISSUE THREAD

**Issue by karussell** [janino-compiler/janino#63]
Thanks a lot for creating janino - helps a lot prototyping some cool ideas in the area of route planning :) !

I'm currently seeking for the best approach to make dozens of helper variables available for a dynamic script like
`edge.get(helperVariable1) * 0.9`

The only parameter that changes per call is `edge`. But the helperVariable1 is not just a constant, it is an instance of an "accessor" class which is already available at creation (or "cook") time. E.g. we can write `edge.get(surface)` and an integer value is returned. So basically these helper variables are known up front (and there could be a lot of them), but we can't just replace them with int or double values up front.

Now, when I use `createFastEvaluator` with 25 parameters I get a nice fast evaluation (in my case 0.06ms/call). (E.g. this is faster compared to "cook&evaluate" with 0.1ms/call,  also with 25 params). But the method of the interface gets really lengthy and is not really customizable. (or is there a trick?)

Is there a better and still fast approach like creating a class with all the helper variables (ClassBodyEvaluator?) as local variables and then make only one method scriptable for the end user?

For example something like this:

```java
public class MyClass {
 HelperParam helperVariable1;
 public  MyClass() {
    // init helperParam
 } 

 public double run(OtherParam otherParam) {
   // USER SCRIPT HERE
   // that uses one or more helper variables
 }
}
```

If this is the way to go. Would I use ClassBodyEvaluator and string manipulation to inject the user script or is there a cleaner method?

I hope this is a bit understandable. Can give more examples if necessary.

Edit: Here is the current [working snippet](https://github.com/graphhopper/graphhopper/commit/f944b6a6044e7ed9c95536c6ab5449520c0135c9) with this approach:

```java
public ScriptWeighting createScriptWeighting(FlexModel model) {
String script = model.getScript();
for (String chars : Arrays.asList("{", "}", "import", "static", "file"))
    if (script.contains(chars))
        throw new IllegalArgumentException("Script contains illegal character " + chars);

if (!script.contains("return"))
    script = "return " + script;
if (!script.endsWith(";"))
    script = script + ";";

try {
    IClassBodyEvaluator cbe = CompilerFactoryFactory.getDefaultCompilerFactory().newClassBodyEvaluator();
    cbe.setNoPermissions();
    cbe.setImplementedInterfaces(new Class[]{ScriptInterface.class});
    cbe.setDefaultImports(new String[]{"com.graphhopper.util.EdgeIteratorState",
            "com.graphhopper.routing.profiles.*"});
    cbe.setClassName("MyRunner");
    cbe.cook("public EnumEncodedValue road_class;\n"
            + "  public EnumEncodedValue road_environment;\n"
            + "  public IntEncodedValue toll;\n"
            + "  public double getMillisFactor(EdgeIteratorState edge, boolean reverse) {\n"
            + script
            + "  }");
    Class<?> c = cbe.getClazz();
    return new ScriptWeighting(model.getBase(), model.getMaxSpeed(), (ScriptInterface) c.newInstance());
} catch (Exception ex) {
    throw new IllegalArgumentException(ex);
}
}
```

But it looks a bit looks a bit hacky.

**Comment by aunkrig** [comment]
Hey Peter,

> I'm currently seeking for the best approach to make dozens of helper variables available for a dynamic script like
> ```
> edge.get(helperVariable1) * 0.9
> ```
> The only parameter that changes per call is `edge`. But the `helperVariable1` is not just a constant, it is an instance of an "accessor" class which is already available at creation (or "cook") time. 

If I get you right, then one solution would be:

Declare a class like
```java
public class HelperVariableContainer {
    public static Accessor helperVariable1 = ...;
    public static Accessor surface = ...;
}
```

Then you'd use the `ExpressionEvaluator` like so:

```java
ee = new ExpressionEvaluator();
ee.setExtendedClass(HelperVariableContainer.class);
ee.setParameters(new String[] { "edge" }, new Class[] { Edge.class });
ee.cook("edge.get(helperVariable1) * 0.9");
ee.evaluate(new Object[] { new Edge() });
```

Does this match your problem?

**Comment by karussell** [comment]
Ah, cool. This could work - thanks!

> ee.setExtendedClass(HelperVariableContainer.class);

If I have this non-static method:

```
public class HelperVariableContainer {
    public static Accessor helperVariable1 = ...;
    public static Accessor surface = ...;
    double get0() { return 0;  }
}
```

will this work?

```
ee.cook("edge.get(helperVariable1) * get0() * 0.9");
```

Or is the main purpose for setExtendedClass some static variables?

**Comment by aunkrig** [comment]
Well, the purpose of `setExtendedClass()` is to configure which class the generated class should extend ;-) ... Like every class that extends another class, it can access the base class's `public` and `protected` members, like class/instance fields, static/non-static methods, and nested types.
If you have expression "parameters" that don't change, then they should not be method parameters, but class variables ("constants").

**Comment by aunkrig** [comment]
BTW, composing cookable text like

```java
    cbe.cook("public EnumEncodedValue road_class;\n"
            + "  public EnumEncodedValue road_environment;\n"
            + "  public IntEncodedValue toll;\n"
            + "  public double getMillisFactor(EdgeIteratorState edge, boolean reverse) {\n"
            + script
            + "  }");
```

is not a good idea, because it opens gates for the `script` to inject all kinds of malicious code.

**Comment by karussell** [comment]
> Like every class that extends another class, it can access the base class's public and protected members, like class/instance fields, static/non-static methods, and nested types.

How would I set the non-static instance fields? (will try your static variable approach in the next days)

> BTW, composing cookable text like

Yes, I feared this :)

**Comment by karussell** [comment]
Thanks a lot! I'm using your last approach with instance variables in `BaseClass` and this works! (I prefer to avoid static variables)

Can I still use a two or more line expression with this? (the `cook(String[])` method does not seem to work - I get an IllegalStateException but it seems this is likely fixed in master. Will there be a new release to maven :) ?)

And currently I would like to hide the scripting behind the interface above `ScriptInterface` that is mainly this method:

```
double getMillisFactor(EdgeIteratorState edge, boolean reverse);
```

and the implementation calls:

```java
try {
    return ((Number) ee.getMethod().invoke(baseClass, edge, reverse)).doubleValue();
} catch (IllegalAccessException | InvocationTargetException e) {
    throw new IllegalArgumentException(e);
}
```

This makes it possible to call `scriptInterface.get(edge, boolean)`. Is this also possible with this ExpressionEvaluator-approach like it was with the ClassBodyEvaluator?

And is the ExpressionEvaluator already secured? Or can I set the security manager only for the expression call? The problem is that we currently do not use a SecurityManager and using `setNoPermissions` makes trouble elsewhere as the SecurityManager is a static variable.

**Comment by aunkrig** [comment]
> And is the ExpressionEvaluator already secured? Or can I set the security manager only for the expression call? The problem is that we currently do not use a SecurityManager and using setNoPermissions makes trouble elsewhere as the SecurityManager is a static variable.

Unfortunately there is no way in Java to configure multiple `SecurityManager`s, e.g. one for Janino-generated classes, not even in younger Java versions. If you cannot install a custom security manager, then you cannot evaluate Janino Expressions/Scripts/... sandboxed. Bummer.

**Comment by aunkrig** [comment]
> Can I still use a two or more line expression with this? (the cook(String[]) method does not seem to work - I get an IllegalStateException but it seems this is likely fixed in master. Will there be a new release to maven :) ?)

See #64.

**Comment by aunkrig** [comment]
> And currently I would like to hide the scripting behind the interface above ScriptInterface that is mainly this method:
```
double getMillisFactor(EdgeIteratorState edge, boolean reverse);
```
> and the implementation calls:
```
try {
    return ((Number) ee.getMethod().invoke(baseClass, edge, reverse)).doubleValue();
} catch (IllegalAccessException | InvocationTargetException e) {
    throw new IllegalArgumentException(e);
}
```
> This makes it possible to call scriptInterface.get(edge, boolean). Is this also possible with this ExpressionEvaluator-approach like it was with the ClassBodyEvaluator?

I don't quite get it, but the trick for using fields and methods of superclasses and implemented interfaces works for `SimpleCompiler`, `ExpressionEvaluator` and `ScriptEvaluator` just as well as with the `ClassBodyEvaluator`.

**Comment by aunkrig** [comment]
Version 3.0.11 is out the door, and includes the fix for this issue.

**Comment by aunkrig** [comment]
Anything left for me to do?

**Comment by karussell** [comment]
No :)

Will have to rewrite this scripting at a later time with security manager enabled. But for experimentation this is already working nicely

**Comment by karussell** [comment]
> BTW, composing cookable text like

Would it be safe if I do such a text manipulation of user input in an expression (instead of the class body)? E.g. to allow the user some abbreviation I could imagine I allow `$(xy)` instead of `something.get(xy)` and would have to do:

```java
cook(expressionString.replaceAll("$(", "expandedStuff.get("));
```

If this is still unsafe, how could it be misused? And would it be safe with a custom SecurityManager?
