### ISSUE TITLE
Compilation Error Messages Generated by JDK

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#65]
As I've pointed out before, Janino's ability to fall back to the JDK as a compiler is fantastic.

However, the locations for the messages that are generated during JDK compilation seem broken. Here's an example. Input source code for `SimpleCompiler`:

```java
public class Example {
  public static void main(String[] unused) {
    test
  }
}
```
And here's the compilation error message thrown:

```
Compilation Failed:
org.codehaus.commons.compiler.CompileException: Line 1, Column 0: not a statement (compiler.err.not.stmt)
	at org.codehaus.commons.compiler.jdk.SimpleCompiler$3.report(SimpleCompiler.java:322)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:593)
	at com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:616)
```
Obviously the message is correct but the location is not. I'm not sure why not. Any ideas?

**Comment by aunkrig** [comment]
Fixed it. Please test.

Man, that `javax.tools` API is sooo awkward...

**Comment by gchallen** [comment]
Thanks! It may take a few days before I can grab the changes. We put Janino in front of 1000 students eager to learn CS so we have to pick our spots as far as when we can bring things down for repairs 👍 .

**Comment by aunkrig** [comment]
Also notice #51 - now `commons-compiler-jdk` finally works with Java 9+!

**Comment by aunkrig** [comment]
Version 3.0.11 is out the door, and includes the fix for this issue.

**Comment by gchallen** [comment]
So this is working perfectly when running in simple compiler mode.

When compiling snippets the line numbers are a bit off—for example an error on line 10 is reported on line 13. I'm assuming this has something to do with how snippet compilation works, perhaps some templating is taking place to wrap the contents in a class definition? Anyway, this is straightforward to fix in postprocessing if it's problematic to fix at the source. Happy to provide a MNWE if you need help reproducing.

**Comment by aunkrig** [comment]
This is more difficult to fix than I first thought — think about the multi-expression / -script evaluator.

**Comment by aunkrig** [comment]
I eventually succeeded... please test!
Added test cases "ReportedBugsTest.testIssue65*()" that demonstrate what has changed.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.
