### ISSUE TITLE
Assignment conversion not possible from type \"java.lang.Boolean\" to type \"java.lang.Object\"\n\

### ISSUE THREAD

**Issue by hiteshbachanna** [janino-compiler/janino#7]
I get the below exception very often, I am evaluating using janio for expression evaluation. I have expression like this ((5<=(264+(2.0*0.0)))), that needs to be evaluated, I am using janio within apache storm, where a bolt does the evaluation, I don't get this exception for every message, but it fail for a large number of message.
I don't see these exception when i try to debug with expression it failed for, looks like this happens when there are lot of thread running, like it always does with apache storm.

`ee = new ExpressionEvaluator();
 ee.cook("((5<=(264+(2.0*0.0))))");
passed = (boolean) ee.evaluate(null);`
This is the piece of code with a bolt that does the evaluation, i pass null to evaluate because all the value in the expression are already there.

Any help on this, would be great.

"error": "org.codehaus.commons.compiler.CompileException: Line 1, Column 21: Assignment conversion not possible from type \"java.lang.Boolean\" to type \"java.lang.Object\"\n\tat org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:10062)\n\tat org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:8988)\n\tat org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:1903)\n\tat org.codehaus.janino.UnitCompiler.access$2100(UnitCompiler.java:182)\n\tat org.codehaus.janino.UnitCompiler$4.visitReturnStatement(UnitCompiler.java:946)\n\tat org.codehaus.janino.Java$ReturnStatement.accept(Java.java:2541)\n\tat org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:958)\n\tat org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:999)\n\tat org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2284)\n\tat org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:822)\n\tat org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:794)\n\tat org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:504)\n\tat org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:390)\n\tat org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:182)\n\tat org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:344)\n\tat org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1136)\n\tat org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:351)\n\tat org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:319)\n\tat org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:358)\n\tat org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:315)\n\tat org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:573)\n\tat org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:471)\n\tat org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:383)\n\tat org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:192)\n\tat org.codehaus.commons.compiler.Cookable.cook(Cookable.java:84)\n\tat org.codehaus.commons.compiler.Cookable.cook(Cookable.java:77)\n\tat com.tgt.wlm.workgen.bolts.RuleEvaluatorBolt.evaluateEpressionsFast(RuleEvaluatorBolt.java:75)\n\tat com.tgt.wlm.workgen.bolts.RuleEvaluatorBolt.execute(RuleEvaluatorBolt.java:53)\n\tat org.apache.storm.daemon.executor$fn__7953$tuple_action_fn__7955.invoke(executor.clj:728)\n\tat org.apache.storm.daemon.executor$mk_task_receiver$fn__7874.invoke(executor.clj:461)\n\tat org.apache.storm.disruptor$clojure_handler$reify__7390.onEvent(disruptor.clj:40)\n\tat org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:439)\n\tat org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:418)\n\tat org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73)\n\tat org.apache.storm.daemon.executor$fn__7953$fn__7966$fn__8019.invoke(executor.clj:847)\n\tat org.apache.storm.util$async_loop$fn__625.invoke(util.clj:484)\n\tat clojure.lang.AFn.run(AFn.java:22)\n\tat java.lang.Thread.run(Thread.java:745)\n"

**Comment by oontvoo** [comment]
Hi hiteshbachanna, thanks for the report. I'd rate this as "unsupported feature", rather than a bug. Janino doesn't support implicit type conversion at the moment.

**Comment by aunkrig** [comment]
Hello hiteshbachanna,

I've been trying to reproduce your problem, but wasn't successful though :-( . I'm afraid that we cannot help you with your problem unless you cannot reduce it significantly, ideally as a (failing) unit test case.

What's more, from the line numbers in your stack trace, it seems like you were using a relatively old version of JANINO. Can you please report which, and/or update to the very latest?


CU

Arno

**Comment by aunkrig** [comment]
This problem never popped up again in the last years, so I close this issue. Rest in peace.
