### ISSUE TITLE
How can I move all local variable declarations to field declarations using janino?

### ISSUE THREAD

**Issue by TsReaper** [janino-compiler/janino#71]
I'm trying to move all local variable declarations to field declarations using janino, so that if I input the following code

```java
class A {
    int a;

    void test() {
        int b = 0;
        int c = 1;
        b += c;
    }
}
```

then parse it to a `CompilationUnit`, and change the AST using a `Traverser`, and unparse it back, I can get

```
class A {
    int a;
    int b;
    int c;

    void test() {
        b = 0;
        c = 1;
        b += c;
    }
}
```
I wrote the following method to create a `Java.FieldDeclaration` from a `Java.LocalVariableDeclarationStatement`:

```java
static Java.FieldDeclaration createFieldDecFromLocalDec(Java.LocalVariableDeclarationStatement lvds) {
    Java.Modifiers modifiers = lvds.modifiers;
    Java.Type type = lvds.type;

    Java.VariableDeclarator[] declarators =
        new Java.VariableDeclarator[lvds.variableDeclarators.length];
    for (int i = 0; i < declarators.length; i++) {
        Java.VariableDeclarator oldDec = lvds.variableDeclarators[i];
        declarators[i] = new Java.VariableDeclarator(
            Location.NOWHERE, oldDec.name, oldDec.brackets, null);
    }

    return new Java.FieldDeclaration(
        Location.NOWHERE, null, lvds.modifiers, lvds.type, declarators);
}
```

But when I run the code, I get the following exception:

`org.codehaus.janino.JaninoRuntimeException: Enclosing scope already set for type "int" at File 'codegen', Line 5, Column 8`

How can I get rid of this exception? Or how can I achieve my goal using janino? Thanks.

**Comment by aunkrig** [comment]
Updated the JANINO home page with a reference to that test case.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
You're welcome!
