### ISSUE TITLE
Compilation failure: CodeContext.java:[528,114] error: ')' expected

### ISSUE THREAD

**Issue by richard-steiger** [janino-compiler/janino#72]
I just cloned the master branch of all projects, and did a "mvn install" in the janino-parent, got the above error message.  Eclipse reports 12 compilation errors in CodeContext, at least some of them are in new lines added in the last commit.   
A (related?) mystery: the directories under src on down are marked "-tmp-", suggesting that these changes are WIP (Work in Process).
Please advise.
Thanks for building this suite!  When I can get a working version, it'll save me many weeks replicating the core functionality.

**Comment by aunkrig** [comment]
That commit was a mistake; just reverted it and everything is now fine. Sorry for the inconvenience.

**Comment by richard-steiger** [comment]
Thank you very much!  I'm looking forward to using Janino!

-rjs
