### ISSUE TITLE
 Operator "&" not defined on types "java.lang.Integer" and "int"

### ISSUE THREAD

**Issue by Yaccc** [janino-compiler/janino#73]
Operator "&" not defined on types "java.lang.Integer" and "int"

how do work??

**Comment by aunkrig** [comment]
Hey,

could you please provide a code example that reproduces the problem? That would be really helpful. Also a stack trace and Janino and JRE version information, please.


Regards, Arno

**Comment by Yaccc** [comment]
> Hey, could you please provide a code example that reproduces the problem? That would be really helpful. Also a stack trace and Janino and JRE version information, please. Regards, Arno
> […](#)
> Am 09.01.2019 um 21:05 schrieb Zhaodong Xie ***@***.***>: Operator "&" not defined on types "java.lang.Integer" and "int" how do work?? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

execute ```new Long(1L)&2 ``` and Similar code，can Reproduce this mistake

**Comment by Yaccc** [comment]
> > Hey, could you please provide a code example that reproduces the problem? That would be really helpful. Also a stack trace and Janino and JRE version information, please. Regards, Arno
> > […](#)
> > Am 09.01.2019 um 21:05 schrieb Zhaodong Xie ***@***.***>: Operator "&" not defined on types "java.lang.Integer" and "int" how do work?? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> execute `new Long(1L)&2 ` and Similar code，can Reproduce this mistake

I see the code ，janino require that both sides expr must be basic types

**Comment by aunkrig** [comment]
Reproduced: `JlsTest.test_15_22__BitwiseAndLogicalOperators()`.

**Comment by aunkrig** [comment]
Fixed; please test!

**Comment by Yaccc** [comment]
> Fixed; please test!

test success ，please deploy it

**Comment by aunkrig** [comment]
Version 3.0.12 is out!
