### ISSUE TITLE
ExprEval

### ISSUE THREAD

**Issue by exprEval** [janino-compiler/janino#74]
Hello, I am trying to use janino for expression evaluation in our system. Wanted to know how can I make it safe to not execute any malicious expression to kill process or change files.

**Comment by aunkrig** [comment]
Hey Expr,

have you read the [Security](http://janino-compiler.github.io/janino/#security) section? If yes, what exactly do you want to know?


CU  Arno

**Comment by aunkrig** [comment]
Ping.
