### ISSUE TITLE
Incorrect Increment with byte Type

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#76]
Consider this code snippet:

```java
byte x = 127;
x++;
System.out.println(x);
x = 127;
x += 1;
System.out.println(x);
```

When run on the standard JDK this produces the expected output: `-128, -128`. However, when run using Janino it produces `128, -128`... ?

**Comment by aunkrig** [comment]
Man... how do you find all these bugs?? Fantastic.
Fixed, please test.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.
