### ISSUE TITLE
Is the janino compiler faster than javac? why?

### ISSUE THREAD

**Issue by Yaccc** [janino-compiler/janino#79]
ask for advice，the performance of janino over javac on compiler，thx！

**Comment by aunkrig** [comment]
Added a statement to the home page:

http://janino-compiler.github.io/janino/#alternative-compiler-implementations

Is that clear? Does it answer your question?

**Comment by aunkrig** [comment]
Ping.

**Comment by Yaccc** [comment]
`is slower by a factor of 12 (measured with the JlsTest unit test case).`?
Can you describe in detail the reasons for the difference in compilation speed?
 thx！
@aunkrig

**Comment by aunkrig** [comment]
See http://janino-compiler.github.io/janino/#alternative-compiler-implementations:

> The suspected reason is that the javax.tools compiler loads the required JRE classes through the classpath, when JANINO uses classes that are already loaded into the running JVM.
