### ISSUE TITLE
Looks like janino causing memory leak, when we compile and load classes for multiple times.

### ISSUE THREAD

**Issue by ram-reddy** [janino-compiler/janino#80]
![image](https://user-images.githubusercontent.com/11553838/52409328-38d2ae80-2afb-11e9-8ca0-b624319de9ef.png)
We are compiling large size source strings (~500 lines of code in each string and  200+ such classes are there to compile) then creating instance of that particular class. 
after quite some time we found that the LinkedHashMapEntry class objects are consuming 50% of our memory (2GB out of 4GB) even though we haven't used LinkedHashMap anywhere in our code explicitly, and lot of byte[] in the heap were referenced from janino classloader.

Any help is appriciated.

**Comment by aunkrig** [comment]
It seems like you are using version 3.0.6 or older. Can you please retry with version 3.0.7 or younger?

**Comment by ram-reddy** [comment]
we are using org.codehaus.janino:janino:3.0.0, is there any issues in the prior versions of 3.0.7, any release notes?

**Comment by aunkrig** [comment]
The release notes are here:

http://janino-compiler.github.io/janino/changelog.html

The were several changes in that code area, so I strongly suggest that you upgrade (if only experimentally).

**Comment by ram-reddy** [comment]
@aunkrig  is there any memory leakage issues in the prior versions? 
is there any breaking changes are there from 3.0.0 to 3.0.7?

**Comment by aunkrig** [comment]
Not that I know — maybe if you use the internal AST or so.

Why don't you just throw in a 3.0.7 and/or the current version and see what happens? All I say is that there were code changes right there, and I am optimistic that these fix the memory leak.

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.
