### ISSUE TITLE
The parallelism of IClassLoader 

### ISSUE THREAD

**Issue by zhouzhb** [janino-compiler/janino#81]
Hi

In the IClassLoader (https://github.com/janino-compiler/janino/blob/c5f874f60208457ad0f5099abdad960a7afbfc81/janino/src/main/java/org/codehaus/janino/IClassLoader.java#L285), there is a synchronized block. It is causing performance problem in our usecase since we have multiple threads that are competing for this lock. Is it possible to make this code path more concurrent by using ConcurrentHashMap or ConcurrentHashSet?

Thank you very much!

**Comment by aunkrig** [comment]
Yes, good point!

Since you have a working test environment, would you mind developing that fix yourself, and I integrate it when it's done?!


CU Arno

**Comment by aunkrig** [comment]
Ping.

**Comment by aunkrig** [comment]
Ping.
