### ISSUE TITLE
Support for JDK 9/10 in Full Compiler

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#88]
Thanks again for all of the great work on this tool—it's fantastic.

Currently both script and simple compilation can both be done similarly using either Janino or the standard Java compiler. This is great since it allows us to fall back to the Oracle JDK when we need certain features, but get all of the performance benefits of Janino when we don't.

However, I don't see how to achieve the same behavior using the full compilation API. This came up previously in #52, and I've pored through the code in `CompilerTest.testInMemoryCompilation()`, but I just can't quite see how to adapt that to use the JDK.

I know that this is a weird request, since the existing in-memory compilation functionality looks like it was built on top of Janino support for a `javac` like command—and of course we already have a `javac` that uses the Oracle or Open JDK 😄 . But it would still be quite convenient for our purposes if it isn't too much work to add...

**Comment by gchallen** [comment]
So I actually got this to work by adding a `compile` method to `SimpleCompiler` in the JDK toolkit that builds multiple compilation units from a single `Map<String, String>`. I have not tested this heavily but it _seems_ to work.

I would be happy to put in a PR with this change for you to clean up and integrate, if you're willing. Currently this duplicates a lot of the anonymous classes used by `cook`, so there is definitely a better way to refactor things.

**Comment by aunkrig** [comment]
Well, I often thought that it might make sense to move the `org.codehaus.janino.Compiler` to a new interface `org.codehaus.commons.compiler.ICompiler`, in analogy with EE, SE, CBE and SC.

The API could have setters for all command line options, and also a "main(args)" method, which parses the command line options and calls the setters.

Is that what you envisage?

E.g.
```
ICompiler compiler = CompilerFactoryFactory.getCompilerFactory(
    "org.codehaus.commons.compiler.jdk.CompilerFactory"
).newCompiler(); // <= new method
compiler.setClasspath(...);
compiler.setDebuggingInformation(true, true, true);
compiler.compile(files);
```

**Comment by gchallen** [comment]
That would be perfect!

**Comment by aunkrig** [comment]
Ok... please hold!

**Comment by aunkrig** [comment]
Hey,

I just committed a first implementation on the TRUNK -- please review, esp. the `ICompiler` interface!

**Comment by aunkrig** [comment]
Ping.
