### ISSUE TITLE
Read and modify line number table during compilation

### ISSUE THREAD

**Issue by PhilipRoman** [janino-compiler/janino#91]
I'm using SimpleCompiler to compile Java source to JVM bytecode (as shown in #19).
I'd like to get the generated line number table and then replace it with my own.
Is there any way to do this?

**Comment by aunkrig** [comment]
There's more than one way to do that... can you give a bit more background what you're trying to do and why you want to modify line number tables?

**Comment by PhilipRoman** [comment]
I'm compiling preprocessed Java source, where some parts are generated but others are provided by users. My main goal is to provide easier debug information in stack traces.

My current solution is to store my own line number table somewhere in the generated code (`public static final int[] table = {...} `), intercept all exceptions and then rewrite the stack trace. This is rather cumbersome and there are lots of corner cases where it does not work, so I'm looking for a way to utilize the built-in line number system.

**Comment by aunkrig** [comment]
`GithubIssuesTest.testIssue91()` provides some template code that demostrates how you get the "right" line numbers into your .class files.

As an important side effect, the code is now Java-injection proof, i.e. you get a `CompileException` for a user expression like `3; } public void evilMethod() { new java.io.File("/etc/passwd").delete()`.

Does that help?

**Comment by PhilipRoman** [comment]
Thanks for the code - I wouldn't have imagined that Janino can manipulate Java code with such elegance! 
This solves my issue. Thank you again!
