### ISSUE TITLE
Provide an option to keep generated code files

### ISSUE THREAD

**Issue by MGelbana-Incorta** [janino-compiler/janino#92]
I understand that the generated code files are deleted when the JVM exists (File.deleteOnExit) but this makes it very hard to debug issues within the generated code after the files are deleted as the process terminates.

**Comment by aunkrig** [comment]
That makes sense... just added another system property `org.codehaus.janino.source_debugging.keep=true` that prevents the temporyray source files from being deleted on exit.

Please test!

**Comment by MGelbana-Incorta** [comment]
I'm using Janino as a part of Calcite, so to test it, I'll have to do so in Calcite and I'm not sure if that'll be a smooth process.
