### ISSUE TITLE
Janino does not preserve generics

### ISSUE THREAD

**Issue by arina-ielchiieva** [janino-compiler/janino#96]
Class example:
```
public class Sample {
 private List<String> listField;
}
```
When compiled using Janino, generics are not preserved:
```
      SimpleCompiler compiler = new SimpleCompiler("Sample", classInputStream);
      Class<?> clazz = compiler.getClassLoader().loadClass(name);
      Stream.of(clazz.getDeclaredFields())
       .map(Field::getAnnotatedType)
       .map(AnnotatedType::getType)
       .forEach(System.out::println);
```
Janino: `java.util.List`
JDK compiler: `java.util.List<java.lang.String>`

**Comment by aunkrig** [comment]
Janino implements generics only half (see "limitations" section on the home page). Thus, the type parameters are missing from the .class files. Sorry.
