### ISSUE TITLE
Is there a convenient way to compile multi class form different package?

### ISSUE THREAD

**Issue by chaokunyang** [janino-compiler/janino#98]
Hi guys,
We want to use `SimpleCompiler` to compile multi class, it seems all these class must share the same package declare. But in our occasion, the class has different packages. Is htere any way to compile these class using `SimpleCompiler`. I know `JavaSourceClassLoader` can do this. But our source class is `String`, and write it to file is not an option. So  is there any way to do this? Any suggestions would be much appreciated.

**Comment by aunkrig** [comment]
Hey Chaokunyang,

using `JavaSourceClassLoader` or `Compiler` doesn't necessarily mean that files are written!

For your use case I would recommend [this pattern](https://github.com/janino-compiler/janino/blob/master/commons-compiler-tests/src/test/java/org/codehaus/commons/compiler/tests/CompilerTest.java#L479).

CU Arno

**Comment by chaokunyang** [comment]
Hi, aunkrig,
     Thanks, the test case `testIssue98` and `testInMemoryCompilation ` both solve my case.
